.dockerignore
.github/workflows/main.yml
.github/workflows/prs.yml
Dockerfile
entrypoint.sh

Build di ogni pr come test aggiuntivo
Ho cambiato il metodo di caching seguendo gli esempi aggiornati ufficiali di docker, vediamo come va
Pushato qui anche il fix dell'entrypoint che abbiamo visto ieri sul mio pc

build: fix docker entrypoint, added pr builds

---

src/config/RichTextEditor/LinkEntity.jsx
src/config/RichTextEditor/Plugins/AnchorPlugin/components/Link/index.jsx
src/config/RichTextEditor/Plugins/AnchorPlugin/components/LinkButton/AddLinkForm.jsx
src/config/RichTextEditor/Plugins/AnchorPlugin/components/LinkButton/index.js
src/config/RichTextEditor/Plugins/AnchorPlugin/index.js
src/config/RichTextEditor/config.js
src/config/Widgets/widgets.js
src/customizations/volto/config/RichTextEditor/Plugins.jsx
theme/_cms-ui.scss

Riportata da https://github.com/RedTurtle/design-volto-theme/pull/613

feat: lighthouse data-element tag on draftjs

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/ja/LC_MESSAGES/volto.po
locales/nl/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/HighlightedContent/Body.jsx
src/components/ItaliaTheme/Blocks/HighlightedContent/Sidebar.jsx

Added a checkbox field to the block sidebar

Feat: added checkbox for data block HighlightedContent

---

razzle.config.js

moment locales restricted to it/en

---

package.json

node_modules/.bin/i18n to package.json scripts

fix: correct the path to script i18n

---

docker-compose.yml
src/components/Image/Image.jsx
src/components/Image/helpers.js
src/components/ItaliaTheme/Blocks/Listing/Commons/ListingImage.jsx

Use `image_scales` metadata as in Plone 6 or https://github.com/RedTurtle/redturtle.volto/pull/62

feat: use image_scales metadata

---

src/customizations/volto/components/theme/View/FileView.jsx
theme/site.scss

New custom layout for FileView component. Module file layout used as model.
[us33487](https://redturtle.tpondemand.com/entity/33487-usability-e-pagine-file-parte-2)

feat: file view custom

---

package.json
src/config/loadables.js
src/customizations/volto-gdpr-privacy/components/ConditionalEmbed/ConditionalEmbed.jsx
src/customizations/volto/components/manage/Diff/Diff.jsx
src/customizations/volto/components/manage/Diff/DiffField.jsx
src/customizations/volto/components/manage/History/History.jsx
src/helpers/htmlDiff.js
src/helpers/index.js
theme/ItaliaTheme/Components/_diffField.scss
theme/_cms-ui.scss
theme/site.scss
yarn.lock

Overhaul del versionamento su io-comune, non funzionante per tutti i campi blocchi e oggetto. Su Plone non funzionano i diff per i RelationListFields, non verranno fixati nel breve. 
Sistemati tutti i bug di Volto che impediscono una corretta visualizzazione delle pagine history e diff
Ho testato abbastanza campi di quelli supportati, ma ovviamente testarli tutti e' impossibile in un tempo umano

Bug 36298 versionamento

---

package.json
src/config/Blocks/listingVariations.js

Implementazione alternativa per #21

Remove new volto headlines configs from listing block

---

src/components/ItaliaTheme/Footer/FooterNavigation.jsx
src/config/italiaConfig.js

New config variable to set on/off the secondary items on automatic menu items

Feat: hide footer sub items

---

theme/ItaliaTheme/Blocks/_completeBlockLinkstemplate.scss

Image style fixed for completeBlockLinkstemplate
https://redturtle.tpondemand.com/entity/36897-immagine-blocco-link-completo

Fix: image complete block links template

---

src/customizations/volto/components/manage/Widgets/ArrayWidget.jsx

Customizzazione temporanea per la fix su volto https://github.com/plone/volto/pull/4200

fix: customized arrayWidget to fix condition of select without vocabulary

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/VenueView/VenueDescription.jsx
src/components/ItaliaTheme/View/VenueView/VenuePublicTimetable.jsx
src/components/ItaliaTheme/View/VenueView/VenueServices.jsx
src/components/ItaliaTheme/View/VenueView/VenueWhere.jsx

feat: Luogo view

---

src/components/Image/Image.jsx
theme/ItaliaTheme/Blocks/_smallblockLinkstemplate.scss

Changed the IntersectObserver inside the Image component to render the images when in the initial viewport view
US: https://redturtle.tpondemand.com/entity/37137-bug-durante-gli-aggiornamenti

Fix: image component & css block link with image

---

src/components/ItaliaTheme/Blocks/TwitterPosts/Body.jsx

https://redturtle.tpondemand.com/entity/37747-assistenza-per-twitter-segnalazione-monitorpa
Removed profile image from twitter block to avoid external request

chore: profile image inside twitter block removed

---

src/config/italiaConfig.js
src/config/volto-gdpr-privacy-defaultPanelConfig.js

https://redturtle.tpondemand.com/entity/38584-nascondere-il-blocco-maps-pnrr
Same as previously made for io-comune-v2

feat: google maps block restricted and removed from privacy options

---

src/components/ItaliaTheme/View/Commons/DownloadFileFormat.jsx

https://redturtle.tpondemand.com/entity/38554-aggiungere-sul-ct-cartella-modulistica-un

feat: added conditional to set pdf download in a new tab

---

theme/_cms-ui.scss
theme/extras/_forms.scss

https://redturtle.tpondemand.com/entity/38846-tipo-di-luogo-tendina-particolare

fix: width on react virtualized

---

theme/_cms-ui.scss
theme/extras/_forms.scss

Doing some tests, I realized that the width: "none" doesn't work properly. Changed to width: 100%.

fix: tendina react virtualized

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/Commons/Gallery.jsx
src/components/ItaliaTheme/View/EventoView/EventoContatti.jsx
src/components/ItaliaTheme/View/EventoView/EventoCosE.jsx
src/components/ItaliaTheme/View/EventoView/EventoUlterioriInformazioni.jsx
src/components/ItaliaTheme/View/EventoView/EventoView.jsx
src/components/ItaliaTheme/View/__tests__/EventoView.test.jsx

fix: change details in event view
feat: change patrocinato_da field from TextLine to RichText; change contatti interni' to 'organizzato da'
feat: update and rebuild i18n catalog
fix: change test

Some event fix

---

src/components/ItaliaTheme/View/DocumentoView/DocumentoDescrizione.jsx

https://redturtle.tpondemand.com/restui/board.aspx?#page=bug/39485

fix: conditional checking added to not break Documento Pubblico view if required fields are missing after v3 migration

---

src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx

https://redturtle.tpondemand.com/entity/39347-customer-satisfaction-class-identification
Added a class to the customer satisfaction container for identification

fix: added a class to identify the customer satisfaction container

---

src/components/ItaliaTheme/Blocks/BandiSearch/Sidebar.jsx

Add new sort indexes in BandiSearch block

---

src/components/Image/Image.jsx

https://redturtle.tpondemand.com/entity/38212-bug-durante-gli-aggiornamenti
applySrcSet() conditional for w removed

Fix: intersection observer

---

src/components/ItaliaTheme/Blocks/Calendar/ListingCalendar.jsx
src/components/ItaliaTheme/Blocks/Calendar/ListingSidebar.jsx
src/components/ItaliaTheme/Blocks/Calendar/schema.js

https://redturtle.tpondemand.com/entity/39690-togliere-i-campi-superflui-nel-blocco
Custom schema created on calendar block to remove some items.

feat: new schema for calendar block

---

src/customizations/volto-form-block/components/Field.jsx

https://redturtle.tpondemand.com/entity/39698-descrizione-di-campo-tipo-lista-in
Added description to select field inside form block

Feat: form select field description

---

src/customizations/volto-form-block/components/Field.jsx

https://redturtle.tpondemand.com/entity/39698-descrizione-di-campo-tipo-lista-in
added description field to select field on form block

feat: added description field to select field on form block

---

src/components/ItaliaTheme/Cards/CardPersona.jsx
src/components/ItaliaTheme/View/Commons/Attachments.jsx
src/components/ItaliaTheme/View/Commons/CuredBy.jsx
src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
src/components/ItaliaTheme/View/DocumentoView/DocumentoAutori.jsx
src/components/ItaliaTheme/View/VenueView/VenueWhere.jsx
theme/ItaliaTheme/Components/_card.scss
theme/ItaliaTheme/Views/_servizio.scss

Fix post rilascio (differenze-io-comune-template)

fix: post release fixes

---

theme/ItaliaTheme/Views/_common.scss

This reverts commit 182fa500863327e2424740b16713d34e68b7ee2e.

Revert "fix: header image height fixed (#103)"

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/ServizioView/ServizioArgomenti.jsx
src/components/ItaliaTheme/View/ServizioView/ServizioView.jsx
src/components/ItaliaTheme/View/index.js

feat: moved topics section from PageHeader and positioned them after Contacts section in ServizioView

us 40102 spostamento argomenti in Ct Servizio

---

src/components/ItaliaTheme/View/PuntoDiContattoView/PuntoDiContattoView.jsx

Fixed intl message values for missing 'id'

Fix pdc intl values

---

theme/ItaliaTheme/Views/_common.scss

Reverts RedTurtle/design-comuni-plone-theme#102

Revert "fix: header image height fixed"

---

theme/ItaliaTheme/Blocks/_hero.scss

https://redturtle.tpondemand.com/entity/40974-blocco-hero-v2
Fixed image preview in edit mode

fix: fixed width and height

---

src/config/Blocks/ListingOptions/index.js
src/config/Blocks/ListingOptions/utils.js
src/config/Blocks/blocks.js
src/config/Blocks/listingVariations.js
src/customizations/volto/components/manage/Form/BlocksToolbar.jsx

fix relativo alla v2 in quanto sempre affetta da questo bug di Volto

V2! fix: copy/paste of volto Blocks

---

src/components/ItaliaTheme/Blocks/Alert/Edit.jsx
src/components/ItaliaTheme/Blocks/Alert/View.jsx
src/components/ItaliaTheme/Blocks/IconBlocks/Edit.jsx
src/components/ItaliaTheme/Blocks/IconBlocks/View.jsx
theme/ItaliaTheme/Blocks/_iconBlocks.scss

- Alert block: view fixed and condition corrected
- Icon Block: Font contrast fixed

fix: alert block and icon block fixes

---

src/config/Blocks/ListingOptions/utils.js

fix: uuid import set

---

theme/ItaliaTheme/Blocks/_alert.scss

Option to set the icon to small - medium - large added to the mobile screen too

feat: small, medium and large icon now on mobile too

---

src/components/ItaliaTheme/Blocks/Calendar/Item.jsx
theme/ItaliaTheme/Blocks/_calendar.scss

Eliminato uppercase calendario + modificata struttura date calendario

Us 41112 eliminare uppercase calendario

---

src/customizations/volto/components/manage/Widgets/DatetimeWidget.jsx
src/customizations/volto/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
theme/_cms-ui.scss

fix: remove custom styles for datepickers, use customizations for DatetimeWidget and RecurrenceWidget to keep previous specs for calendar opening on top in adddate recurrence field

US41900 sovrapposizione calendario a datewidget input

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/config/Blocks/ListingOptions/defaultOptions.js

fix: defaultOptions

---

src/config/italiaConfig.js
src/customizations/volto/components/manage/Blocks/ToC/View.jsx
theme/ItaliaTheme/Blocks/_tableOfContents.scss

Replicated code from https://github.com/RedTurtle/design-comuni-plone-theme/pull/160/files
https://redturtle.tpondemand.com/entity/40582-non-funziona-il-blocco-indice-dei

feat: code replicated from v3 to v2 for the table of contents block

---

src/components/ItaliaTheme/View/Commons/BandoDates.jsx
src/components/ItaliaTheme/View/Commons/Dates.jsx

Fix per SR per blocco elenco date in CT eventi e CT bandi

fix: changed div elements to span elements for SR

---

src/components/ItaliaTheme/View/Commons/BandoDates.jsx
src/components/ItaliaTheme/View/Commons/Dates.jsx
theme/ItaliaTheme/Views/_bando.scss
theme/ItaliaTheme/Views/_evento.scss

Cambiato elemento h5 del card title in p nei componenti:
- Orari e date (CT Evento)
- Tempi e scadenze (CT Bando)
+ aggiustati gli stili

Us 41955 event card ct event

---

theme/ItaliaTheme/Print/_all_pages.scss

https://redturtle.tpondemand.com/entity/41595-stampa-pagine-con-accordion-non-completa
Fixed accordion conteiner and general page-break

feat: managed some page-break for print media

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/BandiSearch/Sidebar.jsx

Questa modifica c'è già su io-comune-pnrr, ma ne abbiamo bisogno qui su io-comune-2
pr di Cekk già mergiata https://github.com/RedTurtle/design-comuni-plone-theme/pull/83
ticket di riferimento [#39402](https://redturtle.tpondemand.com/entity/39402-blocco-ricerca-bandi)

feat: added new sort options in BandiSearch block: effective and modified date

---

src/config/italiaConfig.js

aggiunti api expanders per spostare alcune richieste sul content e su SSR e diminuire il numero di richieste xhr successive al caricamento.
navigation nel nostro caso sembra non venire usato

Aggiunti api expanders

---

src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
theme/ItaliaTheme/Blocks/_calendar.scss

https://redturtle.tpondemand.com/restui/board.aspx?#page=userstory/42451
"Link ad altro" button added to calendar block
--> add to v7.4.X too

feat: button added to calendar block

---

locales/it/LC_MESSAGES/volto.po
src/helpers/Translations/searchBlockExtendedTranslations.js
src/theme/ItaliaTheme/Blocks/_search.scss

fix: missing it translation, workaround for react select missing classnames in build due to design-react-kit mishap

Fix blocco search post feedback redazione

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/TwitterPosts/Body.jsx

https://redturtle.tpondemand.com/entity/42400-sito-in-errore
Condition added when server response is not iterable (map function false)
Condition added when the reduce shows error. Doesn't show the block in the view.

feat: twitter block errors remanage

---

src/theme/ItaliaTheme/Print/_all_pages.scss
src/theme/ItaliaTheme/_common.scss

Aggiunti stili per nascondere icona cookies nelle stampe

fix: hid cookie icon from print mode

---

src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
theme/ItaliaTheme/Blocks/_calendar.scss
theme/ItaliaTheme/_main.scss

https://redturtle.tpondemand.com/restui/board.aspx?#page=userstory/42452
Calendar block arrows fixed

Us42452 calendar arrows mobile

---

src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
src/theme/ItaliaTheme/Blocks/_calendar.scss
src/theme/ItaliaTheme/_main.scss

https://redturtle.tpondemand.com/entity/42452-scroll-eventi-blocco-calendar-mobile
same as https://github.com/RedTurtle/design-comuni-plone-theme/pull/201

Us42452 calendar block arrows

---

src/components/ItaliaTheme/View/ServizioView/ServizioCostiVincoli.jsx

fix: section title is now conditional based on which field is populated

BUG 42131 PNRR - Schede servizio - Campo Costi

---

src/theme/ItaliaTheme/Addons/volto-gdpr-privacy.scss
src/theme/_site-variables.scss

fix: using custom variables in theme, override them if needed in child theme

Us 42196 a11y cookiebanner V3

---

src/components/ItaliaTheme/Blocks/BandiSearch/Body.jsx
src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx
src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx
src/components/ItaliaTheme/Blocks/RssBlock/CardWithoutImageRssTemplate.jsx
src/components/ItaliaTheme/Blocks/UOSearch/Body.jsx
src/customizations/volto/components/manage/Blocks/Listing/ListingBody.jsx

chore: aria-live  on results/no results divs

Us 42240 aria alerts for blocks results v3

---

src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx

https://redturtle.tpondemand.com/entity/43237-logo-er-footer-link

fix: number of slides to scroll on mobile set to 1

---

src/components/ItaliaTheme/Icons/FontAwesomeIcon.jsx

https://redturtle.tpondemand.com/entity/43138-errori-ricerca-icona-blocco-con-icone
Research for icon name error solved for icon block

fix: fontawesome error solved

---

theme/ItaliaTheme/Components/_sharing.scss

fix: accessibility for Actions and Sharing components, contrasts and focus colors

US 42251 focus actions sharing

---

src/components/ItaliaTheme/Blocks/Accordion/Block/EditBlock.jsx
src/components/ItaliaTheme/Blocks/Accordion/Block/ViewBlock.jsx
src/components/ItaliaTheme/Blocks/VideoGallery/Body.jsx
src/components/ItaliaTheme/Blocks/__tests__/Accordion.test.jsx
src/components/ItaliaTheme/Footer/FooterSmall.jsx
src/components/ItaliaTheme/View/Commons/LocationsMap.jsx
src/components/ItaliaTheme/View/Commons/Sponsors.jsx
src/components/ItaliaTheme/manage/Widgets/CanaleDigitaleWidget.jsx
src/config/RichTextEditor/Plugins/AnchorPlugin/components/Link/index.jsx
src/config/italiaConfig.js
src/customizations/volto/components/manage/UniversalLink/UniversalLink.jsx
src/theme/ItaliaTheme/Blocks/_ctaBlock.scss
src/theme/ItaliaTheme/_common.scss
src/theme/_site-variables.scss

feat: add icon to external links for accessibility, configurable in theme settings

us 42252 a11y external link v3

---

src/customizations/volto/components/manage/Blocks/Listing/ListingBody.jsx

Display bg color in listing templates if option property is checked

fix: display listing bg_color

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/CartellaModulisticaView/CartellaModulisticaView.jsx
src/components/ItaliaTheme/View/CartellaModulisticaView/DocRow.jsx
src/components/ItaliaTheme/View/CartellaModulisticaView/SearchBar.jsx
src/components/ItaliaTheme/View/FAQ/FaqFolder/SearchBar.jsx
src/components/ItaliaTheme/View/index.js
theme/ItaliaTheme/Views/_cartellaModulistica.scss

Aggiunta la ricerca nella view della Cartella Modulistica. Filtra i moduli e i documenti in base al loro titolo.
Se pensate possa essere utile si può portare anche nella V3

feat: added live search in CartellaModulisticaView

---

src/theme/ItaliaTheme/_common.scss

fix: focus color on all buttons

 us 42190 focus button V3

---

theme/ItaliaTheme/_common.scss

fix: a11y focus color override for all buttons

us 42190 focus button a11y v1

---

src/customizations/volto/components/theme/View/View.jsx
src/customizations/volto/helpers/Api/Api.jsx
src/customizations/volto/middleware/api.js
src/customizations/volto/middleware/blacklistRoutes.js

https://github.com/plone/volto/pull/4854
https://github.com/plone/volto/pull/5069

Backports v2

---

src/theme/ItaliaTheme/Blocks/_imageBlock.scss

Margin-bottom set to zero when left or right position chose

chore: margin-bottom for left and right positions for image equal zero

---

src/customizations/volto/middleware/blacklistRoutes.js

fix: debugger removed

---

src/components/ItaliaTheme/View/PersonaView/PersonaRuolo.jsx
src/components/ItaliaTheme/View/__tests__/PersonaView.test.jsx

fix: added dates for incarico persona

US 45378 campi incarico persona

---

src/components/ItaliaTheme/View/Commons/OfficeCard.jsx

feat: added pec to office card info

US 45520 pec in card office

---

src/components/ItaliaTheme/Search/Search.jsx
src/theme/extras/_search.scss

fix: incorrect logic for determining if search is ongoing, less layout shifts

US 45368 Caricamento Search 

---

src/components/ItaliaTheme/Blocks/Info/Edit.jsx
src/components/ItaliaTheme/Blocks/Info/Sidebar.jsx

fix: initial color fix

---

src/components/ItaliaTheme/Blocks/Info/Edit.jsx
src/components/ItaliaTheme/Blocks/Info/Sidebar.jsx
theme/ItaliaTheme/Blocks/_info.scss

Code Refactoring
New icon color variable
Now uses css variables
comment with code for sidebar custom colors
others

Us45850 info block

---

src/config/Blocks/blocks.js
src/customizations/volto/components/manage/Blocks/Grid/Edit.jsx
src/theme/ItaliaTheme/Blocks/_gridBlock.scss
src/theme/site.scss

fix: gridBlock edit overlapping when using 4 columns and adding image… block

Bug 45919 Blocco GRID: con 4 colonne sovrapposizione icone caricando img

---

src/components/ItaliaTheme/View/Commons/LocationsMap.jsx

fix: fixed load of locations data in LocationsMap

---

theme/ItaliaTheme/Blocks/_info.scss

DraftJS color fixed
unused css removed

fix: color corretion + file cleaned

---

RELEASE.md

Update file relese.md with the v7.21.0

chore: added the 7.21.0 release info

---

src/components/ReleaseLog/ReleaseLog.jsx

chore: release log title added

---

src/components/ReleaseLog/ReleaseLog.jsx

chore: added title to release-log

---

src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/BodyWrapper.jsx
src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/View.jsx
src/components/ItaliaTheme/Blocks/CTABlock/Block.jsx
src/components/ItaliaTheme/Blocks/CTABlock/View.jsx
src/components/ItaliaTheme/Blocks/Calendar/Body.jsx
src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx
src/components/ItaliaTheme/Blocks/RssBlock/CardWithoutImageRssTemplate.jsx

Aggiunti gli id sui titoli di alcuni blocchi (h2) per permettere di fare delle ancore

chore: added id in h2 title of some blocks to enable anchors

---

src/components/ItaliaTheme/View/CartellaModulisticaView/CartellaModulisticaView.jsx

fix: modulisticaview children non è un documento (non ha items) (v2)

---

RELEASE.md
src/components/ItaliaTheme/Icons/Icon.jsx
src/components/ItaliaTheme/Icons/svg/XTwitterSVG.jsx
theme/ItaliaTheme/Components/_sharing.scss

Aggiornata temporaneamente la nuova icona di Twitter anche sulla v2

chore: updated twitter icon

---

src/components/ReleaseLog/ReleaseLog.css
src/components/ReleaseLog/ReleaseLog.jsx

Added class to release-log component and fixed css

fix: release-log class added

---

src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx
src/components/ItaliaTheme/Blocks/RssBlock/CardWithoutImageRssTemplate.jsx
src/theme/ItaliaTheme/Blocks/_rssBlock.scss

Feed source name added to single card feed.

fix: source added for rss single card

---

RELEASE.md
src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx
src/components/ItaliaTheme/Blocks/RssBlock/CardWithoutImageRssTemplate.jsx

fix: div moved inside condition and release.md

---

CHANGELOG.md
RELEASE.md
package.json
src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/CardWithImageTemplateSkeleton.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/InEvidenceTemplateSkeleton.jsx
src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx
src/components/ItaliaTheme/Blocks/RssBlock/TemplatesSkeleton/CardWithImageRssTemplateSkeleton.jsx
src/components/ItaliaTheme/Blocks/__disabled_tests__/CardWithImageTemplate.test_disabled.jsx
src/components/ItaliaTheme/Blocks/__tests__/CardWithImageRssTemplate.test.jsx
src/components/ItaliaTheme/Blocks/__tests__/CardWithoutImageRssTemplate.test.jsx
src/components/ItaliaTheme/View/Commons/Events.jsx
src/components/ItaliaTheme/View/Commons/GenericCard.jsx

Modificata l'altezza delle immagini nelle card con immagine, per essere in linea con i template di bootstrap-italia

Change card image height

---

RELEASE.md
src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx
src/components/ItaliaTheme/CustomerSatisfaction/Steps/AnswersStep.jsx
src/theme/ItaliaTheme/Components/_customerSatisfaction.scss

Fix di accessibilità sulla form di valutazione del sito, in particolare i focus degli elementi interattivi, eliminato la lettura dei bottoni nascosti, migliorato la lettura dei radio button selezionati.

fix: fixed a11y of customer satisfaction form

---

src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
src/components/ItaliaTheme/View/Commons/EmbeddedVideo.jsx
src/helpers/videoUrlHelper.js
src/helpers/videoUrlHelper.test.js

for this video https://www.youtube.com/watch?v=IgFQuJTGtyM 
preview image was not working because https://img.youtube.com/vi/IgFQuJTGtyM/sddefault.jpg not returns preview image, but https://img.youtube.com/vi/IgFQuJTGtyM/hqdefault.jpg this returns it.

fix: youtube preview image

---

src/customizations/volto/components/manage/Widgets/RecurrenceWidget/EndField.jsx
src/customizations/volto/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx

Fixed recurrence widget 
(apply this https://github.com/plone/volto/pull/5555)

fix: fixed recurrence widget

---

src/config/italiaConfig.js
src/customizations/volto/components/manage/Contents/Contents.jsx
src/customizations/volto/components/manage/Contents/ContentsItem.jsx

Il file Contents.jsx è stato aggiornato alla versione di Volto utilizzata su io-comune v2 ed è stato customizzato per poter inserire nuove colonne nella Content Folder oltre a quelle di default.

feat: added new configuration of content folder columns

---

theme/ItaliaTheme/Blocks/_gridBlock.scss
theme/ItaliaTheme/Views/_common.scss
theme/site.scss

Fix sul blocco grid quando si inseriscono blocchi in full-width

fix: fixed full-width in grid block

---

RELEASE.md
src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx

Riapro qui il ticket di @giuliaghisini

Fix videogallery us50330

---

src/theme/ItaliaTheme/Blocks/_alert.scss
src/theme/_site-variables.scss

Ora sono customizzabili anche i colori del testo del blocco alert

feat: customizable Alert block colors and text color

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/Commons/ContactsCard.jsx
src/components/ItaliaTheme/View/PuntoDiContattoView/PuntoDiContattoView.jsx

Dipende da questa per il backend https://github.com/RedTurtle/design.plone.contenttypes/pull/231

Aggiunta descrizione nei punti di contatto

---

RELEASE.md
src/theme/ItaliaTheme/Blocks/_iconBlocks.scss

The description don't have the minimum contrast with the background.

color contrast - Icon Blocks

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/GridGalleryTemplate.jsx

fix: grid gallery template layout and visual fixes, image is now contained and title does not overflow anymore

Bug 51182 visualizzazione card piccole grid gallery template

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx

fix: alignment of CardPersona images and better layout for tablets, 2 cards max per row at this screen size

fix: alignment of CardPersona images and better layout for tablets, 2 cards max per row at this screen size

---

src/theme/ItaliaTheme/_main.scss

risolto questo problema che si aveva con la navigazione da tastiera:
https://github.com/RedTurtle/design-comuni-plone-theme/assets/51911425/6e9bf176-88e8-4288-ae04-de45f21f03ca

fix: button keyboard focus

---

theme/ItaliaTheme/Subsites/ItaliaTheme/Blocks/_searchSections.scss
theme/ItaliaTheme/Subsites/ItaliaTheme/Blocks/_tableOfContents.scss
theme/ItaliaTheme/Subsites/_mixin.scss

Lista semplice, indice dei contenuti e titolo blocchi ricerca (sottositi)

subsites colors

---

RELEASE.md
package.json
src/components/ItaliaTheme/View/Commons/RenderBlocks.jsx
src/components/ItaliaTheme/manage/Widgets/FileWidget.jsx
src/customizations/volto-form-block/components/Edit.jsx
src/customizations/volto-form-block/components/Field.jsx
src/customizations/volto-form-block/components/FormView.jsx
src/theme/bootstrap-override/bootstrap-italia/_form.scss
yarn.lock

- ora vengono mostrati gli errori per ogni campo:
- sistemata la funzione di 'pulisci i campi della form' per cui alcuni campi non venivano svuotati. 
- se nella configurazione della form non è stato scelti nessun valore tra 'salva' o 'invia' la form non viene mostrata in view, e in edit compare un messaggio di errore.
Questa PR richiede questa https://github.com/collective/volto-form-block/pull/82

View error foreach form field

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/CustomerSatisfaction/CustomerSatisfaction.jsx

fix: changed accessible labels for customer satisfaction

---

package.json
yarn.lock

to fix this https://github.com/collective/volto-form-block/issues/90

chore: updated volto-form-block

---

src/helpers/IconWidget/IconAliasHelper.js

feat: added ppt icon file format

---

src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreEsterno.jsx
src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreInterno.jsx

Da richiesta/segnalazione reggio

fix: remove icon from Organizzatori eventi card

---

package.json
yarn.lock

updated volto-editable-footer to fix display sidebar when editing footer configuration.

chore: updated volto-editable-footer to fix view sidebar in edit config

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Common/SearchFilters/SelectFilter.jsx
src/components/ItaliaTheme/Blocks/EventSearch/DefaultFilters.js
src/theme/ItaliaTheme/Blocks/common/_searchBlockFilters.scss

- Filtro luogo è searchable in blocco EventSearch
- Le opzioni nel menu a tendina son ordinate alfabeticamente
- Aggiustati gli stili per entrambe le opzioni

feat: selectFilter is now searchable for venue search in EventSearch

---

src/components/ItaliaTheme/Blocks/IconBlocks/Block/ViewBlock.jsx

Non ho aggiornato il release.md perchè c'è già un'altra pr che aggiunge l'info sulle migliorie all'accessibilità di del blocco icone

fix: added aria-label for cardReadMore component in iconBlock

---

src/components/ItaliaTheme/AppExtras/TrackFocus.jsx
src/components/ItaliaTheme/MegaMenu/MegaMenu.jsx
src/components/ItaliaTheme/MenuSecondary/MenuSecondary.jsx
src/config/italiaConfig.js
theme/ItaliaTheme/Components/_navigation.scss
theme/site.scss

Aggiunto componente per rimuovere il focus quando si fa click con il mouse.
Questo è una copia della PR per la V3, previamente approvata da Piero. Non ci sono cose nuove o diverse.

trackFocus

---

src/components/ItaliaTheme/View/EventoView/EventoLuoghi.jsx

o altri campi testuali del luogo popolati

fix: view luoghi se c'è solo il nome della sede

---

src/components/ItaliaTheme/View/Commons/ContactLink.jsx

La pagina si rompeva perche la generazione dei link di contatto faceva male il test della regex

fix: error generating contact link

---

src/components/ItaliaTheme/Slider/SingleSlideWrapper.jsx
src/theme/ItaliaTheme/Views/_slider.scss

fix: fix slider focus and external links

---

RELEASE.md
src/config/italiaConfig.js

- Aggiunte delle config per il blocco grid per una corretta visualizzazione dei blocchi elenco al suo interno.

fix: config for block grid

---

src/components/ItaliaTheme/View/Commons/LocationItem.jsx
src/components/ItaliaTheme/View/VenueView/VenueWhere.jsx

- Component OSMMap cambiata a Location per avere la possibilità di scegliere i link sulle PIN
- Piccolo fix per sistemare la condizione per fa vedere il link o no

fix: location for Venue

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/BandiSearch/Body.jsx
src/components/ItaliaTheme/manage/Widgets/SearchSectionsConfigurationWidget/SearchSectionsConfigurationForm.jsx

see https://github.com/RedTurtle/design.plone.policy/pull/65

feat: expandItems (v2)

---

src/components/ItaliaTheme/Blocks/Listing/Commons/CardCalendar.jsx
theme/ItaliaTheme/Components/_card.scss
theme/ItaliaTheme/Views/_common.scss
theme/_mixins.scss
theme/site.scss

fix: view dates for Events in Listing image template

---

src/components/ItaliaTheme/View/Commons/RelatedArticles.jsx
src/components/ItaliaTheme/View/UOView/UOServices.jsx

Come da richiesta di mostrare il paginatore solo se n pagine>1

fix: updated logic to show paginator only if pages>1 in Uo and venue

---

src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderEventDates.jsx

Porting della modifica fatta qui: https://github.com/RedTurtle/design-comuni-plone-theme/pull/739 sull'header eventi.

fix: changed rrule translation in PageHeaderEventDates

---

RELEASE.md

Aggiornato il file release-log

docs: release-log

---

src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx

Messa la didascalia per i video youtube

fix: added caption to youtube videos

---

RELEASE.md
src/components/ItaliaTheme/Blocks/EventSearch/DefaultFilters.js

we need to use values from event_location index and not searching all Venue content type

update search block to use event_location

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/Accordion/Edit.jsx
src/components/ItaliaTheme/Blocks/Accordion/View.jsx
src/theme/ItaliaTheme/Blocks/_accordion.scss

Aggiunti due campi su blocco accordion, uno per il titolo e uno per la descrizione.
tp #50938

feat: title and description for block accordion - v11

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/Gallery.jsx
src/theme/ItaliaTheme/Views/_common.scss

Porting of Slider block styles to CT gallery slider with height fixes + accomodation for figcaption

Bug 58345 ct gallery slider

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/Accordion/Edit.jsx
src/components/ItaliaTheme/Blocks/Accordion/View.jsx
src/theme/ItaliaTheme/Blocks/_accordion.scss

Aggiunti due campi su blocco accordion, uno per il titolo e uno per la descrizione.
tp #50938

feat: title and description added to accordion block - v12

---

RELEASE.md
src/customizations/volto-form-block/components/Sidebar.jsx

Una volta mergiato faccio cherry-pick su main e faccio una PR per il blocco originale

fix: always set form block static_text fields as not required

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/PersonaView/PersonaRuolo.jsx

Changed the name of label and added the info in the section content.

fix: changed end of assignment section label

---

src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx

fix: Slider display

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/Dates.jsx
src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderEventDates.jsx
src/helpers/dates.js
src/helpers/index.js

Porting of: https://github.com/RedTurtle/design-comuni-plone-theme/pull/789

fix: porting of end date in event view

---

RELEASE.md

Added info in corresponding release
It's not formally correct but at the same time, it's an important change that heavily  impacts usability and that clients have no records of.
It might be worth it to think about how to convey important information about BE changes that have no corresponding FE commits but must be notified to clients.

chore: added BE info in release.md bc impacts usability - main

---

RELEASE.md
src/customizations/volto/components/manage/Blocks/Video/Body.jsx

Porting of https://github.com/RedTurtle/design-comuni-plone-theme/pull/788

fix: append / to the end of apiPath because if it hasn't, internal url check for mp4 links fails.

---

src/components/ItaliaTheme/Blocks/Alert/View.jsx

removed class Block from Alert block View

fix: removed class Block from Alert block View

---

RELEASE.md

richiesta dai pm, in accordo con Nicola, non verrà ripristinato perchè va in contrasto con asseverazione

chore: removed additional info from release.md from september

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/customizations/volto/components/manage/Contents/ContentsUploadModal.jsx
src/overrideTranslations.jsx

https://redturtle.tpondemand.com/entity/59721-nota-per-divieto-di-caricare-allegati
pr per 11.x.x https://github.com/RedTurtle/design-comuni-plone-theme/pull/796

fix: added info on contents file upload modal on restraint in servizio-modulistica folder

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderEventDates.jsx

Porting of: https://github.com/RedTurtle/design-comuni-plone-theme/pull/800

fix: removed whole day condition in page header subtitle

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderDates.jsx

Porting of https://github.com/RedTurtle/design-comuni-plone-theme/pull/813/files to main

fix: removed expiration date from event header - main

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx
src/components/ItaliaTheme/Blocks/EventSearch/Sidebar.jsx
src/components/ItaliaTheme/Blocks/UOSearch/Body.jsx
src/components/ItaliaTheme/Blocks/UOSearch/Sidebar.jsx

porting of https://github.com/RedTurtle/design-comuni-plone-theme/pull/815

feat: added checkbox for showing image for all cards in uo search - main

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/Events.jsx

Da mergiare dopo che è stato mergiato BE:
https://github.com/RedTurtle/design.plone.contenttypes/pull/288

feat: added cardCalendar in children events for rassegne

---

src/components/ItaliaTheme/Cards/CardCategory.jsx

And let old label as alternative

Set icon title in CardCategory with content-type name

---

src/components/ItaliaTheme/View/PaginaArgomentoView/PaginaArgomentoView.jsx

https://redturtle.tpondemand.com/restui/board.aspx?#page=bug/63095

fix: uo responsabili image check

---

RELEASE.md
src/theme/ItaliaTheme/Widgets/_blocksWidget.scss

Porting of: https://github.com/RedTurtle/design-comuni-plone-theme/pull/864

fix: changed styles of headings for text editor in cts

---

RELEASE.md
src/theme/_cms-ui.scss

Porting of https://github.com/RedTurtle/design-comuni-plone-theme/pull/869

fix: changed cookies menu button icon

---

RELEASE.md
src/theme/ItaliaTheme/Components/_cardPersona.scss

https://redturtle.tpondemand.com/entity/59103-card-con-immagine-per-ct-persona

Bug 59103 card persona fonts differences

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/EventoView/EventoContatti.jsx
src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreEsterno.jsx
src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreInterno.jsx
src/components/ItaliaTheme/View/EventoView/EventoOrganizzatoDa.jsx
src/components/ItaliaTheme/View/EventoView/EventoPatrocinatoDa.jsx
src/components/ItaliaTheme/View/EventoView/EventoUlterioriInformazioni.jsx

US: https://redturtle.tpondemand.com/entity/64139-visualizzazione-contatti
Goal: reorganize the contacts section in Event CT to group together contacts that refer to the same area (organized by, patrocinato da)

Us 64139 visualizzazione contatti

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/EventoView/EventoContatti.jsx
src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreEsterno.jsx
src/components/ItaliaTheme/View/EventoView/EventoContattiOrganizzatoreInterno.jsx
src/components/ItaliaTheme/View/EventoView/EventoOrganizzatoDa.jsx
src/components/ItaliaTheme/View/EventoView/EventoPatrocinatoDa.jsx
src/components/ItaliaTheme/View/EventoView/EventoUlterioriInformazioni.jsx

porting of https://github.com/RedTurtle/design-comuni-plone-theme/pull/862 for 12

fix: rearranged contacts section for events

---

src/theme/ItaliaTheme/Blocks/_cardWithImage.scss
src/theme/ItaliaTheme/Components/_cardPersona.scss

https://redturtle.tpondemand.com/entity/64749-card-con-immagine-per-ct-persona
no need to add release.md info as this fix has supposedly already been done

fix: card persona fonts

---

src/customizations/volto/helpers/FormValidation/FormValidation.js

https://github.com/RedTurtle/design-comuni-plone-theme/security/code-scanning/3

fix: non backtracking regex

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx
src/config/Blocks/ListingOptions/cardWithSlideUpTextTemplate.js
src/theme/ItaliaTheme/Blocks/_cardWithSlideUpTextTemplate.scss

https://redturtle.tpondemand.com/entity/58329-bug-data-element-per-argomenti-su

fix: added lighthouse id to slideuptext + added overlay link

---

RELEASE.md
src/customizations/volto/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx

porting of: https://github.com/RedTurtle/design-comuni-plone-theme/pull/887

fix: byweekday value added in getFormValues

---

RELEASE.md
src/customizations/volto/helpers/FormValidation/FormValidation.js

https://redturtle.tpondemand.com/entity/65478-regex-url-in-servizio-accedi-al

fix: urlRegex syntax

---

RELEASE.md
src/components/ItaliaTheme/View/PersonaView/PersonaDocumenti.jsx

porting of https://github.com/RedTurtle/design-comuni-plone-theme/pull/889

v3 - fix: added cards to show files uploaded in ct persona trasparenza folder 

---

RELEASE.md

https://redturtle.tpondemand.com/entity/64765-sito-comune-unita-organizzativa-con-due
Just adding the release.md info so the clients know about this feature added from BE. No FE needed.

chore: release.md info on BE change

---

RELEASE.md
src/components/ItaliaTheme/View/ServizioView/ServizioAccedi.jsx
src/theme/ItaliaTheme/Views/_servizio.scss

porting of https://github.com/RedTurtle/design-comuni-plone-theme/pull/891

fix: changed draftjs buttons font in accedi al servizio section in service

---

package.json
src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx
src/components/ItaliaTheme/LoginAgid/LoginAgid.jsx
src/config/italiaConfig.js
src/customizations/volto/components/theme/Footer/Footer.jsx
yarn.lock

Da aggiornare la versione di volto-feedback appena rilasciato prima di mergiare

Bug 65273 feedback noncontentroutes

---

RELEASE.md
src/theme/ItaliaTheme/_home.scss

porting of: https://github.com/RedTurtle/design-comuni-plone-theme/pull/904

Us 58852 h1 display none fix v3

---

RELEASE.md
src/theme/ItaliaTheme/_home.scss

https://redturtle.tpondemand.com/entity/58852-h1-display-none-incorretto-v2-e
used visually-hidden mixin from bootstrap

fix: changed homepage h1 from display none to visually hidden

---

RELEASE.md
src/components/ItaliaTheme/manage/Widgets/HtmlSlateWidget.jsx

La PR https://github.com/plone/volto/pull/6803 è stata mergiata su Volto main il 05/03/2025, quindi le modifiche sono state riportate dentro il file HtmlSlateWidget customizzato da noi.

fix: riportate sul file le modifiche fatte su Volto 18 per il componente HtmlSlateWidget

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/IncaricoView/IncaricoView.jsx
src/components/ItaliaTheme/View/PersonaView/PersonaRuolo.jsx

https://redturtle.tpondemand.com/entity/65792-visualizzazione-informazioni-incarichisplitsplit
Restored previous state

fix: restored original end of assignment label

---

RELEASE.md
src/components/ItaliaTheme/ScrollToTop/ScrollToTop.jsx
src/theme/ItaliaTheme/_common.scss
src/theme/bootstrap-override/bootstrap-italia/_buttons.scss
src/theme/bootstrap-override/bootstrap-italia/_focus.scss
src/theme/bootstrap-override/bootstrap-italia/_headercenter.scss

porting of https://github.com/RedTurtle/design-comuni-plone-theme/pull/915

fix: focus of buttons + focus of inputs + contrast of buttons

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx
src/theme/ItaliaTheme/Blocks/_cardWithSlideUpTextTemplate.scss

https://redturtle.tpondemand.com/restui/board.aspx?#page=bug/66374

fix: title link margin with no category + title style and bg gradient

---

src/helpers/files.js

Fixed the src file for powerpoints icon

fix: changed file src for powerpoint icon

---

src/helpers/files.js

changed label for power point files

fix: changed file icon name for powerpoint icon

---

RELEASE.md
src/components/__tests__/FormValidation.test.js
src/customizations/volto/helpers/FormValidation/FormValidation.js

https://redturtle.tpondemand.com/entity/66697-scheda-servizio-errore-ad-inserimento-link

fix: regex for fragments in formValidation

---

RELEASE.md
src/components/ItaliaTheme/Search/Search.jsx

[US67055](https://redturtle.tpondemand.com/entity/67055-ordinamento-risultati-di-ricerca)

fix: fixed sort_on from url param search view

---

RELEASE.md
src/theme/ItaliaTheme/Blocks/_video.scss

[BUG67386](https://redturtle.tpondemand.com/entity/67386-non-funzionano-i-blocchi-video-di)
Problemi nella visualizzazione del blocco video allineato al centro o fullscreen

fix: fixed full width and center alignment of video block

---

src/components/ItaliaTheme/Blocks/Teaser/ItaliaTeaserBody.jsx

According with @deodorhunter we fix teaser body template

[fix] Fix teaser block

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/AttachmentCardTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/ContentInEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/GridGalleryTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/RibbonCardTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx
src/components/ItaliaTheme/Blocks/Listing/SmallBlockLinksTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/BandiInEvidenceTemplateSkeleton.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/CardWithImageTemplateSkeleton.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/CardWithSlideUpTextTemplateSkeleton.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/ContentInEvidenceTemplateSkeleton.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/GridGalleryTemplateSkeleton.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/InEvidenceTemplateSkeleton.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/RibbonCardTemplateSkeleton.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/SmallBlockLinksTemplateSkeleton.jsx
src/theme/ItaliaTheme/Blocks/_completeBlockLinkstemplate.scss
src/theme/ItaliaTheme/Blocks/_contentInEvidenceTemplate.scss
src/theme/ItaliaTheme/Blocks/_inEvidenceTemplate.scss
src/theme/ItaliaTheme/Blocks/_smallblockLinkstemplate.scss

[US65440](https://redturtle.tpondemand.com/entity/65440-blocco-card-con-immagine-sotto-testata)
Uniformato le varie spaziature e allineamenti dei blocchi Elenco.

fix: fixed spacings and alignments of listing blocks

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
src/theme/ItaliaTheme/Blocks/_bandiInEvidenceTemplate.scss

[BUG68238](https://redturtle.tpondemand.com/entity/68238-dimensioni-diverse-delle-card-bandi-nei)
Ho applicato delle regole con flex perchè col grid i titoli troppo lunghi facevano casino e prendevano più spazio nelle card spingendole ad allargarsi

fix: fixed card width of bandi template

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
package.json
src/customizations/volto-form-block/components/FormView.jsx
src/customizations/volto-form-block/components/Sidebar.jsx
src/customizations/volto-form-block/fieldSchema.js
src/overrideTranslations.jsx
src/theme/ItaliaTheme/Blocks/_form.scss
yarn.lock

US attiva [#67662](https://redturtle.tpondemand.com/entity/67562-form-implementare-campi-visibilicondizioni)
Updated volto-form-block v3.12.0

feat: added new feature of volto-form-block, conditions to show or hide fields

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/customizations/volto/components/theme/RequestTimeout/RequestTimeout.jsx
src/overrideTranslations.jsx

chore: updated requestTimeout with adBlock message

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
src/components/ItaliaTheme/View/BandoView/BandoText.jsx
src/config/Blocks/listingVariations.js

https://redturtle.tpondemand.com/entity/69621-campo-cig-per-ct-bando
da mergiare con 
design.plone.contenttypes
branch = us_69621_campo_cig_ct_bando

feat: cig field in bando ct + bando card

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/RibbonCardTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/SimpleCard/Card/SimpleCardDefault.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/BandiInEvidenceTemplateSkeleton.jsx

Backport della PR V12 https://github.com/RedTurtle/design-comuni-plone-theme/pull/997

fix: add aria-hidden and tabindex -1 to read-more links for better accessibility

---

CHANGELOG.md
RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
package.json
src/actions/contacts.js
src/actions/index.js
src/components/ItaliaTheme/ContactsBlock/ContactsBlock.jsx
src/components/ItaliaTheme/index.js
src/components/ItaliaTheme/manage/Widgets/ContactsWidget/ContactsConfigForm.jsx
src/components/ItaliaTheme/manage/Widgets/ContactsWidget/ContactsConfigWidget.jsx
src/config/Widgets/widgets.js
src/config/italiaConfig.js
src/customizations/volto/components/theme/Footer/Footer.jsx
src/reducers/contacts.js
src/reducers/index.js
src/theme/ItaliaTheme/Components/_contactsBlock.scss
src/theme/ItaliaTheme/Widgets/_contactsConfigWidget.scss
src/theme/site.scss

Widget:
Block in /prova
Block in root

Us 31872 contacts block

---

src/config/Blocks/listingVariations.js

FYI, è stato richiesto di metterlo opzionale a livello di prodotto, da attivare importanto e eseguendo questa nuova funzione esportata nei singoli progetti in cui serve.

Listing table variant is now optional
