RedTurtle/design-comuni-plone-theme

src/components/ItaliaTheme/Footer/FooterInfos.jsx
theme/ItaliaTheme/_main.scss
theme/_cms-ui.scss
theme/bootstrap-override/bootstrap-italia/_footer.scss

fix: editable footer error when omitting title, title no longer required, fix styles and no title column styles
Rese grafiche 
titolo > no titolo
no titolo > titolo
mobile

Fix editable footer errors and style

---

src/components/Image/Image.jsx

fix: IntersectionObserver.unobserve: Argument 1 is not an object

---

theme/ItaliaTheme/Components/_search.scss
theme/site.scss

Z-index fixed on label
[US36666](https://redturtle.tpondemand.com/entity/36666-disallineamento-grafico-nel-risultato-della-ricerca)

fix: label transition fixed

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/config/Views/views.js

Aggiornata la configurazione dei `layoutViewsNamesMapping` perchè creava un bug nella Cartella Modulistica al click sulle actions nella toolbar di sinistra

fix: fixed layoutViewsNamesMapping config

---

src/config/italiaConfig.js
src/config/volto-gdpr-privacy-defaultPanelConfig.js

Block maps removed from blocks options
Google Maps cookies removed from GPDR banner
Left there for future use.

feat: block maps not accessible by default

---

theme/_cms-ui.scss

https://redturtle.tpondemand.com/entity/37761-link-in-colonne-footer-editor-non
Io-comune links uses the $primary color for all links. Now, the links inside draftjs editor (cms settings) on site configurations footer are the io-comune blue (#06c) as default color.

feat: new color for links inside the draftjs editor on footer site config

---

src/components/ItaliaTheme/Blocks/TwitterPosts/Body.jsx
theme/ItaliaTheme/Blocks/_twitterPosts.scss

https://redturtle.tpondemand.com/entity/38642-blocco-twitter-sistemare-la-larghezza-del
The row-full-width class was probably changed in the last bootstrap version, and this block doesn't have the behavior expected. The structure was changed and the Row was removed

feat: block twitter strutture re-done

---

theme/ItaliaTheme/Addons/customerSatisfaction.scss

https://redturtle.tpondemand.com/entity/38772-modifica-testo-nella-sezione-di-feedback
The text wasn't visible on mobile screens because of a wrap inside the label. I was necessary to change the distance between text and button when the input receives the focus.

fix: mobile text not visible

---

theme/ItaliaTheme/Components/_customerSatisfaction.scss

fix: invalid-feedback text was removed by some css in the kit, added it back

US 39507 warning testo customer satisfaction

---

theme/ItaliaTheme/Views/_common.scss
theme/ItaliaTheme/_common.scss

https://redturtle.tpondemand.com/entity/40040-immagine-da-mobile
- display all image when in full-width mode inside mobiles (responsive class) 
- fixed max-height for desktop view
Before:
After:

fix: header image height fixed

---

src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx
src/components/ItaliaTheme/Blocks/RssBlock/CardWithoutImageRssTemplate.jsx
src/components/ItaliaTheme/Blocks/RssBlock/TemplatesSkeleton/CardWithImageRssTemplateSkeleton.jsx
src/components/ItaliaTheme/Blocks/RssBlock/TemplatesSkeleton/CardWithoutImageRssTemplateSkeleton.jsx
src/components/ItaliaTheme/View/Commons/NewsCard.jsx
src/components/ItaliaTheme/View/UOView/UOPeople.jsx
src/components/ItaliaTheme/View/UOView/UOServices.jsx
src/components/ItaliaTheme/View/UOView/UOStructure.jsx
theme/ItaliaTheme/Blocks/_simpleCardTemplate.scss
theme/ItaliaTheme/Components/_card.scss
theme/ItaliaTheme/Views/_common.scss

Tutte le card dovrebbero essere governate da regole specifiche in base al tipo di card, con caratteristiche diverse in base a quanto definito con i Gialli.
Ho controllato le varie card anche nei vari CT e regolato tutto quello che discostava. Dovrebbero essere tutte a posto.
La regola `&:not(.big-heading)` non è più necessaria, l'ho quindi rimossa.

fix: fixed card heading css rules

---

theme/_cms-ui.scss

https://redturtle.tpondemand.com/entity/40157-mettere-il-tooltip-sotto-anziche-sopra
- fix tooltip visibility when the cursor is above the tooltip. The tooltip needs to disappear to show what's underneath

fix: objectBrowser breadcrumb tooltip visibility

---

src/components/Image/__tests__/Image.test.jsx
src/components/Image/helpers.js
src/components/ItaliaTheme/View/Commons/VenuesSmall.jsx

fix: duplicated path in src and srcset if data comes from summary instead of brain
nota: ho lasciato un commentino in VenuesSmall come nota, io non mi ricordo perché è stato lasciato così , se serve o no, ma non funziona

bug 40248: percorso raddoppiato immagini

---

src/components/ItaliaTheme/Blocks/Info/View.jsx
src/components/ItaliaTheme/Icons/DesignIcon.jsx
theme/ItaliaTheme/Blocks/_alert.scss
theme/ItaliaTheme/Blocks/_info.scss

Fixed icon component to show xmlns on Safari/IOS
New colors for draftjs button inside alert and info blocks

Feat: Icon component | Alert and Info Blocks

---

src/components/ItaliaTheme/View/ServizioView/ServizioMetatag.jsx

Abbiamo CT Servizi vecchi che si rompono in visualizzazione
Credo non sia stato gestito l'eventuale mancanza nei dati del campo `sede` che nella nuova struttura del servizio -> ufficio responsabile è un campo obbligatorio.

fix: fixed site of ufficio_responsabile condition

---

src/theme/bootstrap-override/bootstrap-italia/_headerslim.scss

Icona del logout non prende il color ma il fill

fix: fixed logout icon color

---

src/helpers/FormValidation/FormValidationHelpers.js

Durante la validazione alcuni campi di tipo "number" risultavano vuoti anche se compilati
Ho aggiunto una condizione anche per questi fields.

fix: fixed integer field value of FormValidationHelpers

---

src/theme/ItaliaTheme/Blocks/_eventSearch.scss
src/theme/ItaliaTheme/Blocks/_search.scss
src/theme/ItaliaTheme/_main.scss

https://redturtle.tpondemand.com/entity/43017-calendario-eventi-date-calendarietto-sfasate
Event search daypicker weekdays with padding-left

fix: padding weekday date search left padding

---

src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx

https://redturtle.tpondemand.com/entity/43237-logo-er-footer-link
slidestoScroll set to 1 on mobile

fix: number of slides to scroll on mobile set to 1

---

src/customizations/volto/components/manage/Widgets/DatetimeWidget.jsx

sync the base code from
* https://github.com/plone/volto/blob/16.x.x/src/components/manage/Widgets/DatetimeWidget.jsx
* https://github.com/plone/volto/blob/7ec45f7b4d46233236c651f39a951bad8e389184/src/components/manage/Widgets/DatetimeWidget.jsx
(I don't see changes in code in 17.x)

fix: sync datetimewidget customization

---

src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx

https://redturtle.tpondemand.com/entity/44453-errore-visualizzazione-date
It's a little hard to explain... This is where we found the bug: https://www.comune.modena.it/documenti-e-dati/bandi-e-avvisi/bandi-di-concorso/bandi-e-avvisi-di-selezione
Listing block -> no filters -> only documents inside the folder -> The cards inside will be all type "document" even with no filters set. Those cards show creation and modified date (show the current day for both entries), but they shouldn't even appear, only if a filter with "tipo contenuto | documento" was set.
Checkbox "nascondi le date" doesn't work

fix: added condition to SimpleCardTemplate for the creation/modified dates

---

src/config/RichTextEditor/LinkEntity.jsx

Ad esempio, se in un sottosito mettevi del testo con link nel campo 'Testo per l'header del sito', quando inserivi il link dava errore, e se invece il link era presente, quando andavi in edit si spaccava la vista

fix: fix LinkEntity error on create link in WysWidget and in edit

---

src/theme/_cms-ui.scss

Used only .block insted .block.text to render effective the z-index 0 for all blocks

fix: z-index moved to a generic block

---

src/components/ItaliaTheme/View/CartellaModulisticaView/CartellaModulisticaView.jsx

section type Link does not render

fix: section type Link does not render in "CartellaModulistica"

---

src/components/ItaliaTheme/Search/Search.jsx
src/components/ItaliaTheme/Search/utils.js

Sistemato un problema nella paginazione dei risultati della ricerca del sito, per cui se si cliccava su un risultato presente in una pagina che non era la prima (es la pagina 3), quando si faceva back dal browser si ritornava sempre alla prima pagina dei risultati e non alla pagina in cui si era arrivati precendentemente.

fix: fix pagination param in site search

---

src/theme/_cms-ui.scss

Add css to correct slate problem with z-index inside the image block

feat: added z-index 0 to the floating images inside the block image

---

theme/_cms-ui.scss

Add css to correct slate problem with z-index inside the image block

chore: margin-bottom for left and right positions for image equal zero

---

src/customizations/volto/components/manage/Blocks/Listing/withQuerystringResults.jsx

C'era un problema nei blocchi elenco inseriti nel megamenu, per cui se il content della pagina corrente non era ancora stato caricato, o veniva fatto un switch di pagina, per cui lo state del contenuto veniva resettato, non era disponibile la subrequest fatta per quel blocco elenco. 
Ora la subrequest viene eseguita solo se è già stato caricato il contenuto e ogni volta che il contenuto cambia.

fix: fix querystringresults to work properly in megamenu

---

src/customizations/volto/middleware/blacklistRoutes.js

https://github.com/plone/volto/pull/4854 (only blacklistRoutes, no SSR redirect)

fix: backport blacklistRoutes

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/Info/Sidebar.jsx
theme/ItaliaTheme/Blocks/_info.scss

Block info - Color pallet options
Default: Primary, secondary and light gray
Variables created to make easy set up the colors when needed (theme custom)

fix: Us45070 info block theme colors

---

src/components/ItaliaTheme/Breadcrumbs/Breadcrumbs.jsx

Le breadcrumb non devono presentare link nell'ultimo elemento (pagina corrente)

fix: removed link from last breadcrumb element

---

src/customizations/volto/components/manage/Blocks/Listing/withQuerystringResults.jsx

setFirstLoading non veniva impostato a false perchè querystringResult risultava sempre undefined al primo render.
Spostato setFirstLoading(false) in nuovo useEffect con set di dipendenze nuove per triggerare re-render quando la query è conclusa e querystringResult non è più undefined.

fix: changed dependencies for rerender of setFirstLoading

---

src/components/ItaliaTheme/View/Commons/LocationsMap.jsx

Fix per quei casi dove la mappa di un ct UO interno ad un'altra UO non veniva visualizzata.
Ticket [#45604](https://redturtle.tpondemand.com/entity/45604-alcune-volte-le-mappe-non-sono)
Da replicare probabilmente anche su v3.

fix: fixed load of locations data in LocationsMap

---

src/theme/ItaliaTheme/Blocks/_contentInEvidenceTemplate.scss

Prima si vedeva così (sbagliato)
ora si vede così

fix: sistemato il template listing Content in Evidence quando c'è più di un elemento visualizzato

---

src/components/ItaliaTheme/Blocks/ContactsBlock/Block/ViewBlock.jsx
src/components/ItaliaTheme/Blocks/ContactsBlock/Edit.jsx
src/components/ItaliaTheme/Blocks/ContactsBlock/View.jsx

E' stato sistemato l'allineamento orrizzontale del blocco Contatti, in modo che i contatti siano centrati orizzontalmente.
Se infatti c'era un solo contatto, questo rimaneva allineato a sinistra.
Come era prima:
come è stato sistemato:

fix: fix cContacts block horizontal alignment

---

src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
src/theme/ItaliaTheme/Blocks/_iconBlocks.scss

Fissato un problema di disallineamento verticale delle icone nel blocco Icone.
Come si vedeva prima:
come si vede ora:

fix: fix height of icons in Icons Block

---

src/components/ItaliaTheme/Blocks/Listing/ContentInEvidenceTemplate.jsx
src/theme/_cms-ui.scss
src/theme/_cms-ui_container.scss

Sistemata la view dei blocchi in modalità edit, in quanto fuoriuscivano dallo spazio disponibile.
Come era: 
come è ora:

fix: fix container in edit mode

---

RELEASE.md
src/components/ItaliaTheme/View/CartellaModulisticaView/DocRow.jsx

Il problema è che volto non segue correttamente i redirect e se viene linkato un file con @@download ... non si apre correttamente, ma si vede una pagina bianca.

fix: i link in modulistica devono far vedere la remoteUrl e non il link (v2)

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/Listing/SmallBlockLinksTemplate.jsx
src/config/Blocks/ListingOptions/index.js
src/config/Blocks/ListingOptions/smallBlockLinksTemplate.js
src/config/Blocks/listingVariations.js
src/customizations/volto/components/manage/UniversalLink/UniversalLink.jsx
src/theme/ItaliaTheme/Blocks/_smallblockLinkstemplate.scss

Risolve questo problema mettendo in absolute l'icona a11y per il link esterno e prevedendo un impostazione aggiuntiva nel template del blocco per nascondere le icone accessibilita' per i link esterni

feat: Us 46339 link esterni smalllinksblock

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/Listing/SmallBlockLinksTemplate.jsx
src/config/Blocks/ListingOptions/index.js
src/config/Blocks/ListingOptions/smallBlockLinksTemplate.js
src/config/Blocks/listingVariations.js
src/customizations/volto/components/manage/UniversalLink/UniversalLink.jsx
theme/ItaliaTheme/Blocks/_smallblockLinkstemplate.scss

Risolve questo problema mettendo in absolute l'icona a11y per il link esterno e prevedendo un impostazione aggiuntiva nel template del blocco per nascondere le icone accessibilita' per i link esterni

Us 46339 link esterni smalllinksblock v2

---

.gitattributes
src/components/ItaliaTheme/Search/Search.jsx
theme/extras/_search.scss

Fix della logica per mostrare il loader, migliore usabilita' per utenti normali e quelli che richiedono uso di strumenti di accessibilita
Aggiunto .gitattributes per vedere se moriamo meno dietro alla RELEASE.md

Us 45367 no results search usability v2

---

RELEASE.md
src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx

Now the cards have the correct date, not the current day

fix: rss card date

---

RELEASE.md
src/customizations/volto/components/manage/Sidebar/ObjectBrowserBody.jsx
src/customizations/volto/components/manage/Widgets/ObjectBrowserWidget.jsx

Risolto il problema del limite selezioni non rispettato da Volto
Migliorata l'usabilita' con la definizione logica di deselezione e la gestione piu' accurata della chiusura dell'object browser durante le selezioni

Bug 45909 object browser limit

---

RELEASE.md
src/components/ItaliaTheme/View/CartellaModulisticaView/DocRow.jsx
src/theme/ItaliaTheme/Views/_cartellaModulistica.scss

fix: fix a bunch of styling and visual issues in CartellaModulisticaView on desktop and mobile
Prima
Dopo

bug 45358 visualizzazione elementi cartella modulistica

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/customizations/volto/helpers/FormValidation/FormValidation.js
src/helpers/FormValidation/DataGridFormValidationHelpers.js
src/helpers/index.js

fix: add pluggable custom validation for all datagrid fields, not just required ones and applied new validation to timeline_tempi_scadenze

bug45640 Timeline tempi e scadenze

---

RELEASE.md
src/customizations/volto/components/manage/Blocks/Listing/ListingBody.jsx

fix: fixed regression for default classes in SearchBlock view that were overflowing content into columns

bug 47046 regressione view blocco Search

---

src/components/ReleaseLog/ReleaseLog.jsx

Fixed label for the release-log labels with a capital letter for product names 
io-Comune
io-Prenoto
io-Cittadino

fix: tabnav label in Release log

---

RELEASE.md
src/theme/ItaliaTheme/_main.scss
src/theme/ItaliaTheme/_white-header.scss
src/theme/_site-variables.scss
src/theme/bootstrap-override/_bootstrap-italia-site.scss
src/theme/bootstrap-override/bootstrap-italia/_header.scss
src/theme/bootstrap-override/bootstrap-italia/_headercenter.scss
src/theme/site.scss

Con questa modifica è possibile fare un sito con header bianco solo cambiando due variabili. Inoltre ci sono alcuni fix per l'aspetto di un sito mobile (logo e bottone ricerca)
Normale
Bianco (il logo è bianco ma c'è, non l'ho cambiato per questa prova)

Backport white header preset from child themes and fix header mobile

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/Attachments.jsx

Aggiunta condition per attendere la fine del caricamento e far arrivare "children" a RichTextSection, altrimenti a un primo caricamento non viene renderizzata la section --> non appare nel SideMenu

fix: fixed conditions for rendering + fix title tag

---

RELEASE.md
src/components/ItaliaTheme/Blocks/RssBlock/CardWithImageRssTemplate.jsx
src/components/ItaliaTheme/Blocks/RssBlock/CardWithoutImageRssTemplate.jsx
theme/ItaliaTheme/Blocks/_rssBlock.scss

Feed source title added to single card feed.

feat: added source title to single card

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
src/components/ItaliaTheme/View/Commons/BandoStatus.jsx
src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderBando.jsx
src/components/ItaliaTheme/View/index.js

Important
Component created to make possible to customize Bando status translations more efficiently.
It should be deleted after the Volto update.

feat: new BandoStatus component to manage the current status translations

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/Alert/Edit.jsx
src/components/ItaliaTheme/Blocks/Alert/Sidebar.jsx
src/components/ItaliaTheme/Blocks/Alert/View.jsx
src/components/ItaliaTheme/Blocks/__tests__/Alert.test.jsx
src/theme/ItaliaTheme/Blocks/_alert.scss
src/theme/_cms-ui.scss
src/theme/_site-variables.scss

Oltre ad aggiungere la dimensione dell'immagine e ad aver sistemato il widget per il colore, è stata fatta della pulizia nel scss che mi sembrava non applicasse effettivamente stili al componente.

feat: added image size and colorListWidget in Alert block

---

RELEASE.md
src/theme/ItaliaTheme/Subsites/_common.scss
src/theme/ItaliaTheme/Subsites/_homepage.scss
src/theme/ItaliaTheme/_home.scss

Nei sottositi senza nessuno stile applicato si vedeva il titolo della pagina: 
questo perché lo stile della home era applicato solo ai vari template dei sottositi, è stato quindi spostato nel file generale `_home.scss` di io-comune

fix: fixed documentFirstHeading in subsites without style

---

src/components/ItaliaTheme/Blocks/TextCard/SimpleCard/Block.jsx

The simple card had a "footer section" created by an `:after.` Used the `.no-after` class from bootstrap-italia to remove that `:after`

fix: class no-after added to simple card

---

src/theme/ItaliaTheme/Blocks/_cardWithSlideUpTextTemplate.scss

Bugfix
Con il nuovo aggiornamento a volto-17 è stata introdotta una regola alla classe listing-item che sovrascrive l'allineamento del read-more a destra
Il fix è stato aggiunto ad un div figlio `.box-slide-up`

fix: fixed listing block card-slide-text-template read-more alignment

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx
src/theme/ItaliaTheme/Blocks/_cardWithSlideUpTextTemplate.scss

Bugfix
Fix di accessibilità per i link ai read-more nel blocco "Card con test animato" nei sottositi con stile applicato, le regole sono più specifiche per avere i link sempre bianchi su sfondo nero.

fix: fixed a11y of listing block read-more with card-slide-text template

---

src/components/ItaliaTheme/Blocks/CountDown/Background.jsx
src/components/ItaliaTheme/Blocks/CountDown/Edit.jsx
src/components/ItaliaTheme/Blocks/CountDown/View.jsx
src/components/ItaliaTheme/Blocks/NumbersBlock/Edit.jsx
src/components/ItaliaTheme/Blocks/NumbersBlock/View.jsx
src/components/ItaliaTheme/Blocks/__tests__/Countdown.test.jsx

Sistemato il background per i blocchi:
- numeri
- countdown

fix: background image for NumbersBlock and Countdown block

---

RELEASE.md
src/config/Slate/dropdownStyle.scss
yarn.lock

Slate bar wrap when arrives at 100% width

slate bar for small screens

---

RELEASE.md
package.json
yarn.lock

Aggiunto l'addon per fare in modo che nel criterio "posizione" del blocco elenco sia possibile scegliere l'oggetto da linkare con il browser. 
Con questo widget, se si seleziona un oggetto e poi questo oggetto cambia percorso, non è necessario sistemare il blocco elenco. 
https://github.com/RedTurtle/design-comuni-plone-theme/assets/51911425/7e72f939-5396-4fe2-9ad9-f504bb68cbdd

Volto querywidget with browser addon

---

src/config/Blocks/ListingOptions/bandiInEvidenceTemplate.js
src/config/Blocks/ListingOptions/cardWithImageTemplate.js
src/config/Blocks/ListingOptions/cardWithSlideUpTextTemplate.js
src/config/Blocks/ListingOptions/completeBlockLinksTemplate.js
src/config/Blocks/ListingOptions/defaultOptions.js
src/config/Blocks/ListingOptions/inEvidenceTemplate.js
src/config/Blocks/ListingOptions/mapTemplate.js
src/config/Blocks/ListingOptions/photogalleryTemplate.js
src/config/Blocks/ListingOptions/ribbonCardTemplate.js
src/config/Blocks/ListingOptions/simpleCardTemplate.js
src/config/Blocks/ListingOptions/simpleListTemplate.js
src/config/Blocks/ListingOptions/sliderTemplate.js
src/config/Blocks/ListingOptions/smallBlockLinksTemplate.js
src/config/Blocks/ListingOptions/utils.js

Sistemato l'ordinamento delle option nella sidebar del blocco elenco, per fare in modo che il primo campo sia sempre la scelta del template. Probabilmente con l'ultimo aggiornamento di Volto si era scombianto qualcosa. 
Come era: 
Come è ora con questo fix:

fix: listing options order

---

src/theme/extras/_modals.scss

Fix per l'icona di chiusura modale

fix: removed style that hides modal close icon

---

src/components/ItaliaTheme/Blocks/Alert/Edit.jsx
src/components/ItaliaTheme/Blocks/Alert/View.jsx

Per un qualche motivo è stato cambiato il nome della prop in cui viene salvato il colore del blocco alert, e quindi i blocchi esistenti avevano perso il colore.
ora viene testato sia il vecchio nome del campo (color) che il nuovo nome del campo (bg_color), e quando si entra in edit viene impostato come valore di default il valore di 'color' se esisteva, oppure il colore arancione (warning).
E' un fix temporaneo in attesa di capire come muoversi, ed eventualmente pensare ad un upgradestep

fix: backwards compatibility for background color var of Alert block

---

package.json
src/components/ItaliaTheme/Search/ResultItem.jsx
yarn.lock

la libreria react-highlight-words spesso mi ha dato problemi durante la build, visto che è usata solo in un punto e in modo molto semplice, l'ho sostiuita con codice custom.

fix: replace react-highlight-words with simple custom code

---

RELEASE.md
src/components/ItaliaTheme/Blocks/TextCard/CardWithImage/Block.jsx
src/components/ItaliaTheme/Blocks/TextCard/SimpleCard/Block.jsx

Sistemate spaziature e font su mobile, reso visibile la linea di separazione nel blocco Card Semplice che in view non si vedeva.
[Prima]
[Dopo]

fix: fixed font and spaces of Card blocks

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/customizations/volto/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
src/overrideTranslations.jsx

Sistemato l'edit della ricorrenza: si rompeva quando si provava ad editare una ricorrenza.
Sistemata la stringa della ricorrenza nel caso vengano selezionati giorni del mese come 1, 21, 31:
Come era: 
Com
e è ora:

fix: recurrence string and edit recurrence

---

RELEASE.md
src/theme/ItaliaTheme/_main.scss
src/theme/bootstrap-override/bootstrap-italia/_callout.scss

Lo stile "callout" introdotto con un elemento di bootstrap-Italia entrava in conflitto con quello applicato al testo di draftJs.

fix: fixed callout style draftJs

---

src/customizations/volto/components/manage/Blocks/HTML/Edit.jsx

Added type="button" to prevent submit of entire form in CT when pressing pop up toolbar buttons

fix:v2 - added type button to pop up button for html block editor

---

RELEASE.md
razzle.extend.js
src/components/ItaliaTheme/Icons/DesignIcon.jsx

Ho aggiunto gli attributi width e height nel componente dell'icona per totale sicurezza, ma in realtà non dovrebbero mai essere usati perché a monte nell'import degli svg di bootstrap-italia ho aggiunto un plugin di svgo che converte width e height in viewBox, che è migliore perché così l'icona è scalabile infinitamente, mentre senza viewBox non lo è.

fix: bug when importing svg icons without viewBox

---

src/components/ItaliaTheme/Blocks/Listing/GridGalleryTemplate.jsx

The condition for `index % 7 === 3` was missing, and this creates a wrong layout for a card with the class item-3

scale for index 3

---

RELEASE.md
src/theme/ItaliaTheme/Views/_cartellaModulistica.scss

fix: ct Cartella Modulistica layout fixes, handle long text and fix mobile layout
Prima
Dopo

Bug 51205 visualizzazione cartella modulistica

---

src/components/ItaliaTheme/View/Commons/Attachments.jsx

This fix remove annoying log warning

feat: the default maximum b_size allowed in redturtle.volto is 500

---

src/components/ItaliaTheme/View/Commons/WideImage.jsx
src/theme/ItaliaTheme/Views/_common.scss

height: auto
- The new Image component no longer uses the <picture> element as it did before. This change has led to a height issue when the imagePosition variables are set to DocumentBody within the config file.
Result:

set height for DocumentBody images

---

package.json
yarn.lock

fissato un problema nel widget di selezione del path del blocco elenco, per il quale se si inserivano due condizioni per 'Percorso' non manteneva i diversi valori delle condizioni per percorso, ma le eguagliava all'ultimo percorso selezionato

chore: updated volto-querywidget-with-browser

---

src/theme/ItaliaTheme/Blocks/_imageBlock.scss

Rimossa la spaziatura superiore tra le immagini e i paragrafi allineati a destra o a sinistra.

fix: removed top spacing from image block in view

---

RELEASE.md
src/components/ItaliaTheme/Blocks/TextCard/SimpleCard/Block.jsx

Due to respect for the HTML hierarchy, the title of the simple card was changed to h3
- RER request - us51097

Simple card title changed from h4 to h3

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateDefault.jsx

Risolve questo problema:
nel blocco elenco, quando si impostano i filtri per percorso, se poi si clicca sul bottone configurato, non si vede nessun risultato. 
Il motivo era che veniva passata alla query il valore sbagliato del path su cui filtrare.

fix: query for listing path filters

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Calendar/ListingSidebar.jsx
src/theme/ItaliaTheme/Blocks/_calendar.scss

Nascosto il campo "Risultati per pagina" nel blocco Calendario.

chore: hidden pagination size field from calendar block props

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx
src/theme/ItaliaTheme/Blocks/_cardWithImageAndInEvidence.scss

fix: dates layout in CardWithImage template and 4 columns layout

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/actions/getSearchBandiFilters.js
src/components/ItaliaTheme/Blocks/BandiSearch/Body.jsx
src/components/ItaliaTheme/Blocks/BandiSearch/DefaultFilters.js
src/components/ItaliaTheme/Blocks/BandiSearch/FiltersConfig.js
src/components/ItaliaTheme/Blocks/BandiSearch/Sidebar.jsx
src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
src/config/Blocks/ListingOptions/bandiInEvidenceTemplate.js

Modifiche per questa [US51827](https://redturtle.tpondemand.com/entity/51827-modifica-oggetto-bando/comments/109996)
In particolare nel blocco elenco con variazione Bandi in evidenza
- sono stati aggiunte le proprietà per mostrare le Note di aggiornamento anche per i bandi scaduti e per mostrare la Data di ultima modifica
Nella ricerca Bandi
- I campi di tipo Tipologia/Categoria/Ufficio visibili all'utente vengono valorizzati a partire dai bandi specificati nella "Posizione in cui cercare" e non prendono più i valori dal vocabolario,
- sono stati implementati i pre-filtri non visibili dall'utente
- sono stati azzerati i filtri Data quando si atterra in pagina

feat: added pre-filters in BandoSearch and updated user selection filters, added parameters in bando listing block

---

src/theme/ItaliaTheme/Blocks/_cardWithImageAndInEvidence.scss
src/theme/ItaliaTheme/Blocks/_contentInEvidenceTemplate.scss
src/theme/ItaliaTheme/Blocks/_highlitedContent.scss
src/theme/ItaliaTheme/Blocks/_ribbonCardTemplate.scss
src/theme/ItaliaTheme/Blocks/_simpleCardTemplate.scss
src/theme/ItaliaTheme/Components/_card.scss
src/theme/ItaliaTheme/_main.scss
src/theme/_cms-ui.scss

abbiamo questo problema sul focus dei link che vanno su piu righe: 
Con questo fix, trovato negli stili custom per i template agid qui https://italia.github.io/design-comuni-pagine-statiche/sito/lista-risorse.html
risulta tutto piu leggibile:
(non capisco perchè non lo abbiano messo in bootstrap-italia)

fix: focus on link and card title links

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx

Se nel feedback form c'erano degli errori, veniva visualizzato un riquadro bianco senza nessuna indicazione. 
Ora viene mostrato il messaggio di errore

fix: display error in feedback form

---

src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderBando.jsx

Lo stato del bando ora viene letto dall'etichetta passata a backend, richiesto BE aggiornato all'ultima versione

chore: updated bando_state from backend string label

---

theme/ItaliaTheme/_main.scss

Serve a standardizzare il colore su draftjs del pulsante callout con il blocco info (AUSL PC REQUEST)

callout bg

---

RELEASE.md
theme/ItaliaTheme/_main.scss

Il display block su blocco con le tabelle generava un spazio a destra sulla versione mobile. Togliendo il display non ho avuto ulteriori problemi e il problema è sparito.
https://redturtle.tpondemand.com/entity/51937-errata-visualizzazione

table mobile

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/IconBlocks/Sidebar.jsx
src/components/ItaliaTheme/Blocks/IconBlocks/View.jsx

Il titolo e la descrizione, quando cancellati, erano ancora visibile, anche se vuoti.

rich text has content

---

RELEASE.md
src/customizations/volto/components/theme/Login/Login.jsx

Il problema è che returnUrl non leggeva dati corretti
Facendo una prova con una pagina di test, il primo caso (qs.parse(props.location.search).return_url ritornava sempre undefined, rimanevano dunque gli altri due 
La redirect funzionava cliccando sul link "Accedi" perchè si veniva indirizzati a nomepaginaprivata/login, quindi si rientrava nel caso di props.location.pathname.replace etc.etc. (vedi immagine sotto), quindi al posto di /login veniva inserito '', e si tornava alla pagina di origine.
Cliccando sul pulsante invece si veniva indirizzati a homepage/login, quindi la seconda stringa rimaneva vuota e si veniva reindirizzati nuovamente alla homepage invece che alla pagina di provenienza.
Ho risolto inserendo come returnUrl, nel caso il primo caso "fallisca", il path della pagina, …

fix: added returnUrl option for came_from parameter

---

RELEASE.md
src/theme/bootstrap-override/_bootstrap-italia-site.scss
src/theme/bootstrap-override/bootstrap-italia/_buttons.scss

US [51943](https://redturtle.tpondemand.com/entity/51943-a11y-widget-calendario)
Con il focus-visible attivo sui button primary non si vedevano le icone

fix: fixed btn-primary icon with focus-visible

---

src/theme/ItaliaTheme/Views/_common.scss

Sistemata la visualizzazione dell'immagine a tutta larghezza in modalità di edit.
Non veniva considerata la larghezza della sidebar aperta/chiusa (ma solo la larghezza della toolbar) per cui l'immagine risultava shiftata a sinistra in modalità di edit, e non corrispondeva al risultato finale visualizzato al salvataggio.
Ora si vede bene:
https://github.com/RedTurtle/design-comuni-plone-theme/assets/51911425/05e67972-c1d6-4285-b38a-fe3411961c41

fix: image full-width view in edit mode

---

src/components/ItaliaTheme/Blocks/Listing/CardWithImageTemplate.jsx

Di default nella sidebar, l'opzione 'mostra il tipo' è disabilitata per il template del blocco elenco 'Card con immagine',
mentre nel template, il suo default è stato messo a true.
Questo crea problemi di visualizzazioni sui contenuti migrati.
Ho impostato il default della variabile nel template uguale al valore di default della checkbox corrispondente nella sidebar.

fix: default value for show_type in card-with-image-template

---

package.json
yarn.lock

aggiornato volto-form-block per avere:
- la validazione di default degli indirizzi email inseriti nei campi di configurazione della form 'Mittente di default' e 'Destinatari'
- rimosso il campo 'Obbligatorio' dal tipo di campo 'Testo statico' perchè inutile.

chore: updated volto-form-block

---

package.json
yarn.lock

In volto-form-block non era gestito il caso in cui ci sia una variabile null e in alcuni casi si rompeva la form

fix: volto-form-block

---

RELEASE.md
theme/ItaliaTheme/Components/_search.scss

fix: collapse button alignment for filters in Search page

---

theme/ItaliaTheme/Subsites/ItaliaTheme/Blocks/_iconBlocks.scss
theme/ItaliaTheme/Subsites/_mixin.scss

- I sotto siti prendevano i colori del sito principale per il BG del blocco icona

General background color for icons block

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/Listing/AttachmentCardTemplate.jsx
src/config/Blocks/ListingOptions/attachmentCardTemplate.js
src/config/Blocks/ListingOptions/index.js
src/config/Blocks/listingVariations.js

US [50351](https://redturtle.tpondemand.com/entity/50351-blocco-elenco-nuova-variazione-allegati)
Nuova variazione del blocco elenco "Allegati", attraverso l'opzione "Mostra i PDF in anteprima" diamo la possibilità di aprire gli oggetti di tipo file PDF in anteprima in una nuova tab oppure per ogni oggetto di tipo File è possibile scaricarlo.
Per tutti gli altri tipi di oggetto rimane un semplice collegamento
Da mergiare anche sul branch di Slate, dove viene mostrato anche l'info della dimensione e del mime-type

feat: added new AttachmentCardTemplate listing variation

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/actions/index.js
src/actions/resetQuerystringResults.js
src/components/ItaliaTheme/Blocks/BandiSearch/Body.jsx
src/components/ItaliaTheme/Blocks/BandiSearch/DefaultFilters.js
src/components/ItaliaTheme/Blocks/BandiSearch/Edit.jsx
src/components/ItaliaTheme/Blocks/BandiSearch/View.jsx
src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx
src/components/ItaliaTheme/Blocks/EventSearch/Edit.jsx
src/components/ItaliaTheme/Blocks/EventSearch/View.jsx
src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/UOSearch/Body.jsx
src/components/ItaliaTheme/Blocks/UOSearch/Edit.jsx
src/components/ItaliaTheme/Blocks/UOSearch/View.jsx
src/components/ItaliaTheme/View/BandoView/BandoView.jsx

Riferimento alla [US53491](https://redturtle.tpondemand.com/entity/53491-modifica-oggetto-bando)

feat: added new date filter in bandiSearch block, fixed reset of search results and sidemenu layout

---

RELEASE.md
src/config/italiaConfig.js
src/theme/ItaliaTheme/Blocks/_gridBlock.scss

Sistemata la visualizzazione dei blocchi elenco all'interno del blocco griglia. 
Gli elementi dei blocchi elenco sono stati mostrati in modo che in ogni riga ci stiano al massimo due elementi, in quanto lo spazio di una colonna è ridotto.

fix: view Listing blocks inside Grid block

---

RELEASE.md
locales/volto.pot
src/actions/index.js
src/actions/resetQuerystringResults.js
src/components/ItaliaTheme/Blocks/BandiSearch/Body.jsx
src/components/ItaliaTheme/Blocks/BandiSearch/Edit.jsx
src/components/ItaliaTheme/Blocks/BandiSearch/View.jsx
src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx
src/components/ItaliaTheme/Blocks/EventSearch/Edit.jsx
src/components/ItaliaTheme/Blocks/EventSearch/View.jsx
src/components/ItaliaTheme/Blocks/UOSearch/Body.jsx
src/components/ItaliaTheme/Blocks/UOSearch/Edit.jsx
src/components/ItaliaTheme/Blocks/UOSearch/View.jsx

[Bug53645](https://redturtle.tpondemand.com/entity/53645-i-risultati-dei-blocchi-di-ricerca) di riferimento

fix: fixed reset of search blocks results

---

src/theme/ItaliaTheme/_main.scss

su mobile, se il logo era molto largo, veniva tagliato

fix: footer logo responsive height

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/customizations/volto/components/theme/Navigation/Navigation.jsx
src/overrideTranslations.jsx

fix: translated aria-label of menu hamburger icon

---

RELEASE.md
src/components/ItaliaTheme/MegaMenu/MegaMenu.jsx
src/customizations/volto/components/theme/Navigation/Navigation.jsx

Menu dropdown si chiude correttamente quando il percorso è un sottosito con un menu diverso rispetto al sito principale

Megamenu subsite

---

src/config/italiaConfig.js
src/customizations/volto/components/manage/UniversalLink/UniversalLink.jsx

now UniversalLink opens external links in new tab by default if 
config.settings.openExternalLinkInNewTab = true
default value setted for openExternalLinkInNewTab is true

feat: use config.settings.openExternalLinkInNewTab

---

RELEASE.md
src/components/ItaliaTheme/Slider/NextArrow.jsx
src/components/ItaliaTheme/Slider/PrevArrow.jsx

@Wagner3UB 
yes yes I know what you're thinking: basta togliere aria-hidden=true, non serve impostarlo a false, è di default
Però senza attributo non impostato esplicitamente a false, NVDA continua a leggere "vuoto" invece dell'aria-label

fix: changed aria-hidden to false

---

src/components/ItaliaTheme/View/Commons/ContactsCard.jsx

Rimosso il load del Punto di Contatto nel componente ContactsCard perchè inutile e creava problemi con il validatore agid. 
Verificati tutti i punti in cui viene usato:
- Unità Organizzativa
- Servizio
- Evento
- Persona
- Luogo

fix: no load PuntoDiContatto in ContactsCard

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx

yes yes I know what you're thinking: basta togliere aria-hidden=true, non serve impostarlo a false, è di default
Però senza attributo non impostato esplicitamente a false, NVDA continua a leggere "vuoto" invece dell'aria-label

fix: changed aria-hidden to false for slider arrows

---

RELEASE.md
src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx
src/components/ItaliaTheme/Blocks/EventSearch/DefaultFilters.js

Richiesto il porting della customizzazione fatta su Parma per permettere di eliminare il filtro date dalla ricerca eventi.
Inoltre, aggiunti i parametri per ordinare gli eventi per data di inizio in ordine crescente.

fix: changed default filters in EventSearch DataFilter + query parameters

---

src/helpers/getItemsByPath.js

this fix handles this cases:
if items contains a rule for path  _"/**test**"_
if i navigate to _"/**test**-number-one"_ now this path doesn't matches
if i navigate to _"/pippo/pluto/**test**"_ now this path doesn't matches (before it was matching and it was wrong)

fix: match path

---

src/config/italiaConfig.js

Better handle /diff route regexp as non-content route because otherwise "cms-ui" styles are applied also on contents that starts with "diff" like "diffusione".

Fix "/diff" regexp

---

theme/ItaliaTheme/Addons/customerSatisfaction.scss

Textarea dentro alla customer satisfaction non si vedeva su chrome.

fix: border color and width

---

src/components/ItaliaTheme/View/CartellaModulisticaView/CartellaModulisticaView.jsx
src/components/ItaliaTheme/View/CartellaModulisticaView/DocRow.jsx
theme/ItaliaTheme/Views/_cartellaModulistica.scss

- Mostra la ricerca in testata nella Cartella Modulistica solo se c'è il flag attivato nel contenuto
- evidenza il testo cercato 
- se faccio una ricerca gli elementi collassabili che rimangono collassabili nei risultati (perchè c'è piu di un elemento al suo interno che corrisponde alla ricerca) vengono esplosi. 
- se nel content-type è stato flaggato il campo 'non_collassare_gli_elementi' non vengono mostrati i bottoni per il toggle e gli elementi sono tutti esplosi

feat: CartellaModulistica view improvements

---

theme/ItaliaTheme/Blocks/_gridBlock.scss

Customizzazione per i blocchi elenco dentro al blocco grid.
Le customizzazione sono le stesse messe sulla V3, più 2 (inEvidenceTemplate + smallBlockLinksTemplate) per sistemare anche queste visualizzazioni.

fix: added css for listing blocks inside grid block

---

src/components/ItaliaTheme/MegaMenu/MegaMenu.jsx

c'era questo problema (segnalato dalla rer)
Se nel megamenu ci sono due link che hanno la parte iniziale del link uguale al path in cui sei, te li seleziona entrambi nel caso in cui ti trovi in uno dei due path.
Ad esempio, se i link sono
/a/b/test
e
/a/b/test-pippo
se vado su /a/b/test-pippo mi selezionava entrambi
da riportare anche sul 12.0.x

fix: megamenu active item

---

RELEASE.md
src/components/ItaliaTheme/Blocks/EventSearch/DefaultFilters.js

Il problema è che per popolare quella select viene fatta questa query:
```
dispatch: {
path: subsite ? flattenToAppURL(subsite['@id']) : '/',
portal_types: ['Venue'],
fullobjects: 0,
b_size: 10000,
subrequests_name: 'venues',
additionalParams: {
sort_on: 'sortable_title',
sort_order: 'ascending',
},
```
Le info del subsite però vengono prese dallo store di redux. Al momento del rendering della pagina, lo store redux per `state.subsite?.data` ha inizialmente un oggetto vuoto, visto come truthy, che quindi imposta come path  `flattenToAppURL(subsite['@id']) (= undefined) `
Solo dopo viene impostato a null quando si rende conto che non si tratta di un sottosito, e a questo punto però il path è già stato impostato e la search è fallita perchè ha /undefined/ come parametro
In teoria i …

fix: added check for subsite to path in venue query for events search filter

---

src/components/ItaliaTheme/Breadcrumbs/Breadcrumbs.jsx
src/components/ItaliaTheme/Footer/FooterInfos.jsx
src/components/ItaliaTheme/Footer/FooterMain.jsx
src/components/ItaliaTheme/Footer/FooterSmall.jsx
src/components/ItaliaTheme/Header/HeaderCenter.jsx
src/components/ItaliaTheme/Header/HeaderSlim/HeaderSlim.jsx
src/components/ItaliaTheme/Header/ParentSiteMenu.jsx
src/helpers/index.js
src/helpers/url.js

è stato sistemato il link alla home page nel caso di siti multilingua.
Prima puntava sempre a '/' e poi in automatico veniva fatta la redirect alla radice di lingua.
Ora i link alla homepage puntano alla radice della lingua corrente.

fix: home link per languageRootFoolder

---

src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx
src/components/ItaliaTheme/BrandText/BrandText.jsx
src/components/ItaliaTheme/BrandTextFooter/BrandTextFooter.jsx
src/components/ItaliaTheme/Header/HeaderCenter.jsx
src/components/ItaliaTheme/Header/HeaderSlim/HeaderSlim.jsx
src/components/ItaliaTheme/Logo/Logo.jsx
src/components/ItaliaTheme/Slider/NextArrow.jsx
src/components/ItaliaTheme/Slider/PrevArrow.jsx
src/customizations/volto/components/theme/Navigation/Navigation.jsx

Risolto problemi di stili nel footer dovuti a markup html diversi previsti da bootstrap-italia tra header e footer.
Risolto problemi di retrocompatibilità del nostro css con i loghi dei sottositi, serve mantenere la `<figure class="icon">` oppure rifattorizzare il css per funzionare senza ma poi diventa un breaking change, oltre che altro tempo speso.
Risolto alcuni warning che si ottenevano durante il rendering degli slider.

Fixed site settings style issues and minor warnings

---

src/theme/_cms-ui.scss

nel widget dei blocchi (ad esempio quando editi il testo di una news), si vedeva la toolbar della tabella sopra alle celle di intestazione e dava problemi durante l'editing delle celle: 
ora la toolbar è stata spostata piu in alto

fix: blocks widget table block toolbar position

---

RELEASE.md
src/config/italiaConfig.js

Set maxFileUploadSize to 100mb in BINARY bytes, not decimal, see volto/helpers/FormValidation.js.validateFileUploadSize error message
```
messages.fileTooLarge, {
limit: `${Math.floor(
config.settings.maxFileUploadSize / 1024 / 1024,
)}MB`,
}
```

fix: set maxFileUploadSize config setting to 100mb

---

src/config/RichTextEditor/ToolbarButtons/TextSizeButton.jsx
theme/_cms-ui.scss

Sistemato bug nella sidebar con draftJs l'elenco puntato non veniva stilizzato e l'icona del TextSize nella toolbar non si vedeva con il title applicato.

fix: fixed list style format in sidebar context and TextSize icon

---

RELEASE.md
src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx
src/components/ItaliaTheme/Blocks/UOSearch/Body.jsx

EventSearch and UOSearch still retained old queries for info. That meant that the info required from database asked for fullobjects, not only generating a very heavy query, but also requiring the wrong image fields. 
Changed it with the same logics as listing blocks, with metadata: "_all" to retain informations for UOSearch which also require other info to render cards.

fix: removed fullobjects from query in EventSearch and UOSearch blocks

---

src/theme/ItaliaTheme/Components/_metadata.scss
src/theme/ItaliaTheme/Widgets/_blocksWidget.scss

fix: add clear:both to bottom-metadata and richtext-blocks classes

---

src/customizations/volto/components/manage/Blocks/Listing/ListingBody.jsx

Rimosso lo sfondo per i card, il comportamento per l'intero blocco rimane lo stesso.
Test fatto su ogni singolo blocco tipo "search"

fix: removed bg from template-wrapper inside block search

---

src/components/ItaliaTheme/View/NewsItemView/NewsItemText.jsx
src/config/Views/views.js

questa modifica non ha nessun effetto diretto sul prodotto, è quindi senza effetti collaterali e dal mio punto di vista si potrebbe già fare il merge
se presente un prodotto per i comunicatistampa (WIP rer.ufficiostampa/volto-rer-ufficiostampa Modena e RER) usa la vista Notizia per quel CT.

feat: vista news su ct ComunicatoStampa

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/Commons/Dates.jsx
src/overrideTranslations.jsx

Quando la ricorrenza è mensile/annuale ed è impostato il parametro "Si ripete ogni x giorno-della-settimana" es. (Si ripete ogni 3° martedì del mese/del mese di novembre), la stringa prodotta non era in un italiano corretto ("ogni mese di 2 domenica fino al 15 dicembre 2024")
Siccome non è possibile agire all'interno della libreria rrule e delle logiche che regolano la funzione toText che converte i parametri di recurrence in testo, plasmati comunque su espressioni inglesi, sono andata a sovrascrivere le traduzioni specifiche per questo caso e per il locale 'it'.
E' un po' una toppa, però o si mette mano alla libreria e si crea una funzione interna a ioComune che calcola le stringhe di ogni singolo caso della ricorrenza, oppure si agisce in questo modo solo per l'italiano e per questo …

Rrule monthly recurrence text

---

theme/ItaliaTheme/Blocks/_photogallerytemplate.scss

Sistemata la mancanza di allineamento dentro photogallery

fix: removed align-item from slick-track

---

RELEASE.md
src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx

Self-explanatory
Quello che succedeva da segnalazione cliente, è che impostando la data di fine come filtro nella ricerca eventi, veniva impostata quella data come data di fine evento, invece che la data di fine evento.
Correggendo la query e chiamando tutti i dati, questo problema si "risolve", ma a breve arriverà un'altra pr per come vengono calcolate le date nelle card perchè abbiamo notato altri problemi a riguardo nel debuggare questa richiesta.

fix: metadata field in EventSearch

---

src/customizations/volto/actions/vocabularies/vocabularies.js

https://github.com/RedTurtle/design-comuni-plone-theme/pull/738
aggiunto un check per evitare di dare la url sbagliat nel caso il vocabolario venga marcato contestuale ma chiamato senza contesto
(la modifica è già presente nella PR su volto)

paranoid check contextual_vocab

---

RELEASE.md
src/components/ItaliaTheme/View/UOView/UOMetadati.jsx
src/components/ItaliaTheme/View/UOView/UOView.jsx
src/components/ItaliaTheme/View/index.js

The component that provides info on the CT last update had been deleted in this commit:
https://github.com/RedTurtle/design-comuni-plone-theme/commit/d562d1f2de714fef8cca3ba639b340135ce0da0a#diff-242becc687a024ddc511a8f392480e9f979de57446ba23b2b091c07cc222f5ad
to make room for other "Ulteriori Informazioni" fields.
Added a new section in the page to restore the Metadata without creating a new item in the SideMenu component.
Used the same logics as in the ServizioView

fix: restored Metadata component in UO View

---

RELEASE.md
src/components/ItaliaTheme/View/UOView/UOMetadati.jsx
src/components/ItaliaTheme/View/UOView/UOView.jsx
src/components/ItaliaTheme/View/index.js

(Duplicate of PR https://github.com/RedTurtle/design-comuni-plone-theme/pull/753 for branch main)
The component that provides info on the CT last update had been deleted in this commit:
https://github.com/RedTurtle/design-comuni-plone-theme/commit/d562d1f2de714fef8cca3ba639b340135ce0da0a#diff-242becc687a024ddc511a8f392480e9f979de57446ba23b2b091c07cc222f5ad
to make room for other "Ulteriori Informazioni" fields.
Added a new section in the page to restore the Metadata without creating a new item in the SideMenu component.
Used the same logics as in the ServizioView

fix: branch main - restored Metadata component in UO View

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/BandoView/BandoApprofondimenti.jsx
src/components/ItaliaTheme/View/Commons/Attachment.jsx

Aggiunto data di modifica dentro attachment.jsx per mostrare la data dentro i documenti allegati nei CT Bando
ps: Serve redturtle.bandi aggiornato - Sentire @cekk

feat: Last modified document

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/Blocks/VideoGallery/Block/EditBlock.jsx
src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
src/components/ItaliaTheme/Blocks/VideoGallery/Edit.jsx
src/components/ItaliaTheme/Blocks/VideoGallery/Sidebar.jsx
src/components/ItaliaTheme/Blocks/VideoGallery/View.jsx

Cambiata label per la didascalia video
Aggiunto checkbox per mostrare o meno la didascalia
https://redturtle.tpondemand.com/entity/57952-gallery-video

feat: video gallery option for caption

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/CustomerSatisfaction/FeedbackForm.jsx
src/config/italiaConfig.js
src/customizations/volto/components/theme/Footer/Footer.jsx

Nelle pratiche il titolo della form di feedback deve essere "quanto ti è stata utile questa pagina" nei vari step e "quanto ti è stato utile questo servizio" solo dopo aver sottomesso la pratica.
Visto che lo stato è gestito nella pratica, viene fatto in modo che feedbackform possa gestire un title custom, rimosso dal footer per alcuni CT il feebackform (ie ModelloPratica), questi ct gestiranno in autonomia la componente FeedbackForm

fix: custom feedback form title (v11)

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/components/ItaliaTheme/View/PersonaView/PersonaDocumenti.jsx

Added fields for Trasparenza in CT persona.
As requested, the new fields allow to attach files.
Mergeable after merging the design.plone.contenttype branch `us_57188_new_fields_for_persona`

fix: added trasparenza fields to CT Persona

---

RELEASE.md
src/config/Blocks/ListingOptions/cardWithSlideUpTextTemplate.js

Parlato con Nicola, per ora rimuoviamo questo campo da questa variazione per evitare che i clienti la usino in futuro. Lui si occuperà di farla cambiare ai clienti che attualmente ce l'hanno su.
Più avanti con un po' più di budget si farà il rework del blocco

fix: removed id_lighthouse field in cardWithSlideUpTextTemplate

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/Gallery.jsx
src/theme/ItaliaTheme/Views/_common.scss

Porting of: https://github.com/RedTurtle/design-comuni-plone-theme/pull/763 for branch 11.x.x

fix: slider styles + arrows in ct gallery

---

src/theme/ItaliaTheme/Blocks/_form.scss

https://www.w3.org/WAI/WCAG21/Techniques/css/C38
questa WCAG controlla che gli stili segnalati (flexbox, max-width, width) vengano usati per fittare gli elementi sullo schermo quando lo zoom arriva anche a 400%.
Aggiunto max-width alla row dei form e ai form-field per far sì che tutti i campi fittino nello schermo senza dover fare scroll orizzontale con alti livelli di zoom

fix: added max-width attribute to row to fit elements within page when zoomed in

---

RELEASE.md
src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx

Since parent events in "Rassegne" are just containers for the "appuntamenti", the Event Search block by default only shows the children events when returning results.

fix: added filter for eventi rassegne in Event Search

---

src/components/ItaliaTheme/Blocks/BandiSearch/Body.jsx
src/components/ItaliaTheme/Blocks/Common/SearchFilters/DateFilter.jsx
src/components/ItaliaTheme/Blocks/EventSearch/Body.jsx

- Stesso filtro per blocchi cerca diversi + Input filter data per blocchi cerca 
- Screen reader message per filtri blocchi ricerca
utilizzando uuid o l’id del blocco (univoci) dentro l’attributo startDateId="start-date-filter" e endDateId="end-date-filter" si può risolvere la questione dell’id duplicato.

fix: added block id to date ids to ensure unique field ids

---

RELEASE.md
src/components/ItaliaTheme/Blocks/VideoGallery/Block/ViewBlock.jsx
yarn.lock

Non si vedeva l'anteprima per i video dentro il blocco video gallery.
Ho usato il codice della V3 per risolvere il problema della non visualizzazione dell'anteprima sulla V3
#58488

fix/refactor: resolve bug in the video gallery block doing a refactor code structure

---

src/components/ItaliaTheme/Blocks/ArgumentsInEvidence/BottomBody.jsx
src/components/ItaliaTheme/Footer/FooterInfos.jsx
src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderEventDates.jsx
src/components/ItaliaTheme/View/Commons/RelatedItems.jsx
src/components/ItaliaTheme/View/Commons/SideMenu.jsx
src/components/ItaliaTheme/View/PuntoDiContattoView/PuntoDiContattoView.jsx
src/components/ItaliaTheme/View/VenueView/VenueWhere.jsx

Mauve segnala problemi principalmente su CT con layout “fisso” (a differenza dei blocchi che sono interscambiabili e difficili da gestire a livello di disposizione).
Per risolvere, controllare i casi segnalati da Mauve, e utilizzare tag <p> con classe dell’heading di cui si vuole utilizzare lo stile per assicurare un ordine giusto sull’utilizzo dei vari tag <h>
Es. Elemento che indica la ricorrenza in CT evento è un <h4>, posto subito dopo un <h1>. L’ordine dei tag <h> in questo caso non è corretto. Utilizzare un <p class=”h4”> garantisce la correttezza a livello di html, ma con stili conformi a quelli descritti da agid.

fix: used p with h classname to ensure correct heading order

---

RELEASE.md
src/theme/ItaliaTheme/Addons/volto-gdpr-privacy.scss
src/theme/ItaliaTheme/Blocks/common/_searchBlockFilters.scss
src/theme/ItaliaTheme/Widgets/_reactSelect.scss
src/theme/ItaliaTheme/_common.scss
src/theme/_site-variables.scss
src/theme/bootstrap-override/bootstrap-italia/_focus.scss
src/theme/bootstrap-override/bootstrap-italia/_headercenter.scss

Il focus arancione scuro scelto non è sempre visibile su tutti i colori.
Questo problema era già noto dalle prime analisi. Siamo in attesa di un riscontro e di una decisione da parte di Bootstrap Italia per l’aggiornamento del kit.
Si era parlato di una proposta di focus nero e bianco in modo che il contrasto fosse assicurato su ogni tema, ma non ci sono state decisioni lato design kit e questa decisione è rimasta in sospeso.
Success case: Comune di Siracusa.
Scelta di prodotto: doppio colore

fix: changed focus color

---

RELEASE.md
src/customizations/volto/components/theme/View/LinkView.jsx

Whenever a spid user logs in, it will be part of the AuthenticatedUsers group but no roles will be assigned.
There are no other info on whether a user is logged in through spid or if it's an operator of some sort.
Added the customization to the LinkView Plone/Volto component at lines indicated at top of file
https://redturtle.tpondemand.com/restui/board.aspx?#page=userstory/58460

fix: added condition for spid user link redirect

---

RELEASE.md
src/customizations/volto/components/manage/Blocks/Video/Body.jsx

Append / to the end of apiPath because if it hasn't, internal url check for mp4 links fails.

Fix internal url check in video blocks body

---

RELEASE.md

Added info in corresponding release
It's not formally correct but at the same time, it's an important change that heavily impacts usability and that clients have no records of.
It might be worth it to think about how to convey important information about BE changes that have no corresponding FE commits but must be notified to clients.

chore: added BE info in release.md bc impacts usability

---

RELEASE.md
src/components/ItaliaTheme/Header/HeaderSlim/LoginButton.jsx
src/theme/ItaliaTheme/_main.scss

Risolto un problema di visualizzazione grafica per il bottone di login all'area personale per alcune specifiche dimensioni di schermi (992px-1200px)
Before
After

fix: arlogin styles in 992px-1200px media query space

---

src/components/ItaliaTheme/View/ViewUtils.jsx

Quando si aveva abilitata l'opzione "updateSideMenuOnLoadingBlocks" per una vista di un content-type, se veniva mostrata una gallery con molti elementi la pagina si freezzava e il browser si impallava perchè il mutation observer veniva reinizializzato di continuo a causa probabilmente dei continui rerender del componente della gallery. 
Togliendo la prop "subtree" all'observe dell'observer gli diciamo di rimanere in ascolto solamente i suoi figli diretti (che è quello che a noi interessa per costruire i titoli del menu laterale"

fix: freeze page with gallery

---

RELEASE.md
package.json

When applying settings for "Only technical cookies" in gdpr control panel, the page would break everytime the cookie banner is opened.
The code would break as there was no conditional chaining in the profiling cookies section of the code.
The new version of volto-gdpr-privacy has fixed that and does not cause any other issues in the control panel

fix: updated volto_gdp_privacy

---

RELEASE.md
src/components/ItaliaTheme/Icons/DesignIcon.jsx
src/components/ItaliaTheme/Icons/FontAwesomeIcon.jsx
src/components/ItaliaTheme/Icons/Icon.jsx
src/theme/ItaliaTheme/_main.scss

Sistema questo comportamento causato da bug di webkit e mala gestione del rendering con lazy-loaded icons esclusivamente su Safari, WebKit, iOS.
Migliorato il sistema di lazy loading delle icone di bootstrap-italia per non causare 4x render rispetto al necessario con una mappa globale degli import

Bug 60364 universal link safari and lazy icons

---

src/components/ItaliaTheme/View/BandoView/BandoApprofondimenti.jsx
src/components/ItaliaTheme/View/Commons/LocationsMap.jsx
src/components/ItaliaTheme/View/Commons/Module.jsx
src/components/ItaliaTheme/View/Commons/Modules.jsx
src/components/ItaliaTheme/View/PaginaArgomentoView/PaginaArgomentoView.jsx

Removed getContent from all CT and CT common components.
RelatedNews, Venue e VenueSmall use getContent but are not used by any CT
Before merging, must merge and release BE branch us55252_upgrade_serializer
I did not update the release.md as it is not something that impacts usability

Us 55252 remove get content from view components

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderEventDates.jsx

whether the event is marked as "whole day" or not, it won't change the logic or how the date is shown in the subtitle of the event ct.
Only the start date is shown and the new recurrence management provides enough conditions to manage each different case.
having the whole day condition makes it so both the first string and the second string are rendered. Could have managed the whole day condition in another way but still, it does not impact how date should be shown

fix: removed whole day condition in page header subtitle

---

RELEASE.md
src/components/ItaliaTheme/Icons/DesignIcon.jsx
src/customizations/volto/components/manage/UniversalLink/UniversalLink.jsx
src/theme/ItaliaTheme/_main.scss

Sistema questo comportamento causato da bug di webkit e mala gestione del rendering con lazy-loaded icons esclusivamente su Safari, WebKit, iOS.
Migliorato il sistema di lazy loading delle icone di bootstrap-italia per non causare 4x render rispetto al necessario con una mappa globale degli import

Bug 60364 universal link safari and lazy icons slate

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderDates.jsx

As requested, the expiration date has been removed from the header of the event to avoid generation confusion with actual event dates

fix: removed expiration date from event header

---

RELEASE.md
src/components/ItaliaTheme/Header/HeaderSearch/SearchModal.jsx
src/theme/extras/_modals.scss

quando si faceva una ricerca nel sito tramite la popup di ricerca che si apre cliccando sul pulsante presente nell'Header del sito, al submit, la popup si chiudeva e se il caricamento della pagina dei risultati richiedeva tempo, si rimaneva in "stallo" senza nessuna informazione evidente, sulla pagina da cui era partita la ricerca. Per l'utente era fuorviante perchè non era chiaro se la ricerca era partita o meno.
Ho evitato che la popup si chiudesse e ho aggiunto in overlay un loader.
https://github.com/user-attachments/assets/0ba54034-5a07-4c41-9a76-38d2a49e46cd
su v2 non è necessario portarla perchè ho gia fatto io

fix: no close search popup when redirecting to results page

---

src/components/ItaliaTheme/MegaMenu/MegaMenu.jsx

Il menu non si chiude quando si fa click su un "show more" button su megamenu mobile. La pagina si carica, ma non sparisce il menu.

fix: added closeMenu to it-external on megaMenu

---

src/theme/_cms-ui.scss
src/theme/extras/_tables.scss

Sistemati gli stili delle tabelle per renderli uniformi tra edit e view:
Ora, se in view il risultato è questo:
quando si va in edit non c'è corrispondenza di stili:
ma con le nuove regole aggiunte in questa pr, gli stili corrispondono anche in edit:
(richiesto dalla RER)

fix: table styles in edit mode

---

src/customizations/volto-form-block/components/View.jsx

from https://github.com/collective/volto-form-block/pull/122
(fifth attempt)

Backport ISO dates fix in volto-form-block

---

src/components/ItaliaTheme/Blocks/Calendar/Body.jsx

Sistemato l'ordinamento di default degli elementi nel blocco calendario . 
Ora vengono ordinati per data/ora di inizio. 
Fare cherry-pick anche sulla 11. 
Non è strettamente necessario, ma è legata a questa pr di Be: https://github.com/RedTurtle/design.plone.contenttypes/pull/290/files

fix: default sort for day-items in Calendar block

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Common/SearchFilters/SelectFilter.jsx
src/components/ItaliaTheme/Blocks/EventSearch/DefaultFilters.js
src/customizations/volto/actions/vocabularies/vocabularies.js

The Events Search block location filter takes options from a vocabulary populated by all the venues linked to an Event in the path selected through the Sidebar.
The vocabulary query had the classic Plone limit of 25 so in case of higher numbers of results, it cut the list to 25.
Added a parameter to the SelectFilter that is set to 25 by default, but that can be changed or removed (by setting -1) when necessary

fix: removed query b_size limit for event_location vocabulary

---

src/customizations/volto/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx

Sistemato un problema nel calcolo delle ricorrenze, non venivano calcolate correttamente, e veniva messa solamente la data finale, perchè la data iniziale non veniva impostata. 
Esempio del problema: 
ho un evento che inizia il 8/12 e finisce il 29/12, voglio impostare una ricorrenza settimanale la domenica, ma come giorni della ricorrenza mi vengono proposti solo il 29 dicembre. Invece dovrei vedere anche 8,15 e 22 dicembre. 
https://github.com/user-attachments/assets/794ad387-faf1-4091-adc5-a8dca73554d7
Esempio della soluzione: 
vengono correttamente aggiunte le date 8,15 e 22 dicembre (oltre al 29)
https://github.com/user-attachments/assets/37044920-f25d-4b23-afc6-a6b6b9810645
se le modifiche sulle ricorrenze erano state fatte anche per la 11, va fatto cherry pick li …

fix: start date in recurrences

---

RELEASE.md
src/helpers/files.js
src/helpers/files.test.js

Prima
Dopo
Non chiaro perche' in caso di pdf si ritorni da backend text/plain, ma facendo affidamento sull'url ignoriamo anche questa casistica buffa.
Aggiunti i test per evitare regressioni, da portare con cherry su 11.x.x

fix: getFileViewFormat regex inconsistencies with different filenames that included @@download/**, added anti-regression tests

---

locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/overrideTranslations.jsx

Aggiunte le traduzioni per il blocco tabella. 
E' stata fatta anche una pr su volto-slate per aggiungere le traduzioni in italiano che fin'ora mancavano (https://github.com/plone/volto/pull/6563)
(il nome del blocco nella sidebar "Table block" non si può tradurre perchè è scritto fisso nello schema)
us https://redturtle.tpondemand.com/entity/59841-blocco-tabella-le-opzioni-della-sidebar

fix: Table block translations

---

RELEASE.md
src/theme/ItaliaTheme/Widgets/_blocksWidget.scss

https://redturtle.tpondemand.com/entity/64168-gestione-h1-h6split
The styles of the headings applied to text added by text editor in the cts were not cohesive with the correct semantic heading order. i.e. by putting the correct order of headings (h2 > h3) the h3 heading was bigger and bolder than the h2.
To guarantee a correct order even from a style pov and to prevent users from using the wrong semantic order to have a pleasant effect, the styles of the headings in the text editor sections of cts have been improved
all styles are accessibility-safe

fix: changed styles of headings for text editor in cts

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/CardWithImage/CardWithImageDefault.jsx
src/theme/ItaliaTheme/Blocks/_cardWithImage.scss

porting of: https://github.com/RedTurtle/design-comuni-plone-theme/pull/866

fix: improved alignment of topic links in card with image

---

RELEASE.md
src/theme/_cms-ui.scss

https://redturtle.tpondemand.com/entity/62342-sistemare-pannello-di-controllo-cookie-banner
semantic-ui-react icons can't render up and down arrows (even though the icon code inside the content css property is correct, by looking at fontawesome), but they can render left and right. I replaced the icon code for those icons and then rotated the icon.
(the same logic has been applied to the control panel for the menu and secondary menu)

fix: changed cookies menu button icon

---

RELEASE.md
src/theme/ItaliaTheme/Blocks/_gridBlock.scss

Disposti verticalmente le colonne di un blocco griglia su mobile. 
Richiesto dalla RER.
come era prima su mobile: 
come è ora su mobile:

fix: grid block on mobile

---

RELEASE.md
locales/en/LC_MESSAGES/volto.po
src/components/ItaliaTheme/Blocks/Listing/AttachmentCardTemplate.jsx
src/config/Blocks/ListingOptions/attachmentCardTemplate.js
src/customizations/volto/components/manage/UniversalLink/UniversalLink.jsx

segnalato dalla RER. Us. 64372
Nel template del blocco elenco 'Allegati' l'opzione "Mostra i PDF in anteprima" non aveva alcun effetto, i file venivano sempre scaricati.
Ora, con le modifiche fatte, i file pdf vengono aperti in anteprima se c'è il flag su quella opzione.
Per tutti gli altri file, continuano ad essere valide le regole precedenti, ovvero quelle definite dal config per ogni tipo di file.
Aggiunta una condizione in UniversalLink per aggiungere i parametri @@Download o @@display-file solo se non sono già presenti nell'url

fix: listing template attachments download and display file

---

RELEASE.md
src/components/ItaliaTheme/Blocks/ContactsBlock/Block/EditBlock.jsx
src/components/ItaliaTheme/Blocks/ContactsBlock/Edit.jsx
src/components/ItaliaTheme/Blocks/IconBlocks/Block/EditBlock.jsx
src/components/ItaliaTheme/Blocks/IconBlocks/Edit.jsx
src/components/ItaliaTheme/Blocks/NumbersBlock/Block/EditBlock.jsx
src/components/ItaliaTheme/Blocks/NumbersBlock/Edit.jsx
src/theme/ItaliaTheme/Blocks/_accordion.scss
src/theme/ItaliaTheme/Blocks/_contacts.scss
src/theme/ItaliaTheme/Blocks/_ctaBlock.scss
src/theme/ItaliaTheme/Blocks/_iconBlocks.scss
src/theme/ItaliaTheme/Blocks/_numbers.scss
src/theme/ItaliaTheme/Blocks/_subblocks-edit.scss
src/theme/_mixins.scss

Migliorata l'accessibilità in edit (navigazione da tastiera) dei blocchi Contatti, Icone, Numeri
Allego video del risultato ottenuto con la navigazione da tastiera. 
Prima di questi fix non venivano correttamente selezionati i blocchi quando si passava da un blocco ad un altro. 
https://github.com/user-attachments/assets/7667a764-15ce-4109-98e2-62fb37905fa6
Richiesto dalla RER

fix: a11y of Contacts, Icons, and Numbers block

---

RELEASE.md
src/components/ImageWithErrors/ImageWithErrors.jsx
src/components/ItaliaTheme/Blocks/Listing/CardWithImage/CardWithImageDefault.jsx
src/components/ItaliaTheme/Blocks/Listing/Commons/ListingImage.jsx
src/components/ItaliaTheme/Blocks/Listing/CompleteBlockLinksTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/ContentInEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/GridGalleryTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/PhotogalleryTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/SliderTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/SmallBlockLinksTemplate.jsx
src/components/ItaliaTheme/Cards/CardPersona.jsx
src/components/ItaliaTheme/View/Commons/GenericCard.jsx
src/components/ItaliaTheme/View/Commons/LocationItem.jsx
src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
src/components/ItaliaTheme/View/Commons/Sponsors.jsx
src/components/ItaliaTheme/View/Commons/VenuesSmall.jsx
src/customizations/volto/components/theme/View/ListingView.jsx
src/helpers/images.js
src/helpers/index.js

Fix di tutti i check image truthish, in quanto image e' un istanza di un React Element e non puo' essere mai falsish, non rappresenta il possibile ritorno del componente mai.
Da finire di testare per bene, ho iniziato qui https://v3.io-comune.redturtle.it/test-martina/test-fix-img-null-check-bug
PS: Alcune occorrenze simili esistono anche in Volto tipo PreviewImage, se li usiamo e' da scoprire, non ci sono arrivata ancora

wip: fixing all image checks and ListingImage

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/LocationItem.jsx
src/components/ItaliaTheme/View/Commons/OfficeCard.jsx
src/components/ItaliaTheme/View/Commons/VenuesSmall.jsx
src/theme/ItaliaTheme/Components/_cardLocationItem.scss
src/theme/bootstrap-override/_bootstrap-italia-site.scss
src/theme/bootstrap-override/bootstrap-italia/_avatar.scss

https://redturtle.tpondemand.com/entity/64576-visualizzazione-card-con-avatar
Stato attuale di quelle card
LocationItem e VenuesSmall
OfficeCard
Si aggiornano i layout html e gli stili in modo da fixarli e renderli conformi al figma nelle dimensioni degli avatar
LocationItem e VenuesSmall
Office Card
Link agli esempi testati:
- https://v3.io-comune.redturtle.it/test-sabrina/every-ct/notizie
- https://v3.io-comune.redturtle.it/test-sabrina/every-ct/evento
- https://v3.io-comune.redturtle.it/test-sabrina/every-ct/servizio
- https://v3.io-comune.redturtle.it/test-sabrina/every-ct/persona-pubblica
- https://v3.io-comune.redturtle.it/test-sabrina/every-ct/luogo
- https://v3.io-comune.redturtle.it/test-sabrina/every-ct/documento
- https://v3.io-comune.redturtle.it/test-sabrina/every-ct/bando
- …

fix: layout and style issues, customized bootstrap-italia/_avatar.scss due to nonsense scaling for avatar-lg sizes, figma compliant

---

RELEASE.md
src/components/SelectInput/SelectInput.jsx

Condizione per la Label per i select ripristinata. La select non può rimanere senza label visibile, basta non essere collegata al componente via aria-labeledby.
Il merge con la cancellazione:
https://github.com/RedTurtle/design-comuni-plone-theme/pull/856
Il problema attuale, con i select senza label: 
https://www.regione.emilia-romagna.it/search?SearchableText=agevolazioni&group=bandi

fix: rollback label selectinput

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Accordion/Block/ViewBlock.jsx

Durante un'analisi di a11y su io-sanità è venuto fuori questo fix da fare che ripropongo anche qui. 
Se nel testo dell'accordion ci sono dei link, questi sono navigabili da tastiera anche quando l'accordion è chiuso, e non deve poter succedere. 
Questo fix risolve il problema

fix: a11y accordion block

---

RELEASE.md
src/theme/ItaliaTheme/Blocks/_search.scss

Nella faccetta del widget 'select' del blocco 'Cerca'
compariva la scrollbar (su firefox su windows) perchè l'input era piu alto dello spazio disponibile.

fix: prevent scrollbars in select-facet of search block

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/PageHeader/PageHeader.jsx
src/components/ItaliaTheme/View/VenueView/VenueView.jsx

Sistemata la visualizzazione del campo 'nome alternativo' del content-type luogo. 
In visualizzazione si vedeva per un attimo poi spariva, con un effetto di "sfarfallio". 
Vedi un esempio qui: 
https://v3.io-prenoto.redturtle.it/luogo-di-giulia
Segnalato dalla RER

fix: render of nome_alternativo for Venue view

---

RELEASE.md
src/customizations/volto/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx

https://redturtle.tpondemand.com/entity/64779-eventi-bug-su-ricorrenze
The recurrence was saved correctly when first setting it. When re-opening the widget modal, it would retrieve the formValues by getFormValues which did not add the byweekday field therefore not saving that field upon saving again

fix: byweekday value added in getFormValues

---

RELEASE.md
src/components/ItaliaTheme/View/PersonaView/PersonaDocumenti.jsx

https://redturtle.tpondemand.com/entity/64998-saltata-la-modifica-del-ct-persona
I did not remove any content set from the specific CT Persona fields as some Comuni might have already uploaded them, and those fields can still be used.
Before merging this, make sure the BE is merged too:
us64998

fix: added cards to show files uploaded in ct persona trasparenza folders

---

RELEASE.md
src/customizations/volto/components/manage/Blocks/Search/SearchBlockView.jsx
src/customizations/volto/components/manage/Blocks/Search/layout/LeftColumnFacets.jsx
src/customizations/volto/components/manage/Blocks/Search/layout/RightColumnFacets.jsx
src/theme/ItaliaTheme/Blocks/_search.scss
src/theme/bootstrap-override/_bootstrap-italia-site.scss
src/theme/bootstrap-override/bootstrap-italia/_form-select.scss

Sistemati gli stili del focus delle select nel blocco 'Cerca'.
Le select hanno infatti al loro interno un input per fare la ricerca dei valori della tendina, che inizialmente ha larghezza quasi nulla, e al focus appariva una doppia linea verticale ravvicinata.
Aggiunto inoltre lo scroll automatico all'inizio dei risultati quando vengono applicati dei filtri da parte dell'utente.

fix: search block focus styles and scroll into view results when apply filters

---

src/components/ItaliaTheme/Blocks/IconBlocks/Block/ViewBlock.jsx
src/components/ItaliaTheme/Blocks/IconBlocks/View.jsx
src/components/ItaliaTheme/Blocks/NumbersBlock/View.jsx
src/theme/ItaliaTheme/Blocks/_iconBlocks.scss
src/theme/ItaliaTheme/Blocks/_numbers.scss

https://redturtle.tpondemand.com/entity/65546-titoli-blocco-icone-e-numeri
no pr for 11.x.x because it's for RER and therefore only on 3.3.x
Also, 11.x.x has redraft and it'd be a mess. Sooner or later they will all be migrated to 12.x.x, and no accessibility tool has ever pointed it out.

fix: added h tags for icons and numbers block

---

src/components/ItaliaTheme/Blocks/Accordion/Block/ViewBlock.jsx

rimosso il toggle sull'onfocus del contenuto dell'accordion. 
In visualizzazione, al click su un link presente nell'accordion, l'accordion si chiudeva

fix:  toggle accordion on link inside click

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/BandoDates.jsx
src/components/ItaliaTheme/View/Commons/Dates.jsx

migliorata la lettura da parte degli screen reader delle date presenti nella timeline del dettaglio del ct Bando e Evento. 
Alcuni screen reader leggevano quelle date senza spazi, e di conseguenza leggevano l'anno come "duezeroduequattro"
us: 65254

fix: a11y bando and events timeline

---

RELEASE.md
src/config/Slate/Blockquote/index.js
src/theme/ItaliaTheme/_main.scss

sistemata l'accessibilità dei blockquote. 
In particolare, alcuni screenreader non riconoscono il tag blockquote, quindi leggono il testo al suo interno tutto appiccicato al testo che lo precede e lo segue. 
Alcune indicazioni sull'accessibilità per i blockquote suggeriscono di wrappare il testo al suo interno in un <p> 
us: 65254

fix: Blockquote a11y

---

src/components/ItaliaTheme/View/PageView/PageView.jsx
src/components/ItaliaTheme/View/PageView/Placeholder/HeaderEnd.jsx
src/components/ItaliaTheme/View/index.js

Aggiunto un nuovo placeholder al termine della testata del ct Pagina
La rer ha bisogno di inserire un pulsante in quella posizione. 
us: 65254

feat: Page placeholder HeaderEnd

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/Module.jsx

and show as a Modulo content type; editors request to handle file cut/paste into ct documento
blocked by:
https://github.com/RedTurtle/design.plone.contenttypes/pull/299 (merged)
design.plone.contenttypes 6.3.4 [to be released]

feat: allow ct document to contains also File content types 

---

RELEASE.md
src/theme/ItaliaTheme/Blocks/_gridBlock.scss

sistemata la visualizzazione su mobile dei template dei blocchi listing dentro ai blocchi griglia. 
Su mobile non venivano linearizzate le card, che se hanno testi lunghi o sono un po' piene di info non si capiva molto bene
Per semplicità metto lo screenshot del template card semplice, ma ho verificato anche gli altri template che erano gestiti nel blocco griglia.
Come era prima: 
Come è ora:
us: 65441

fix: Fix grid listing on mobile

---

RELEASE.md
src/components/ItaliaTheme/ScrollToTop/ScrollToTop.jsx
src/theme/ItaliaTheme/_common.scss
src/theme/bootstrap-override/bootstrap-italia/_buttons.scss
src/theme/bootstrap-override/bootstrap-italia/_focus.scss
src/theme/bootstrap-override/bootstrap-italia/_headercenter.scss

https://redturtle.tpondemand.com/entity/64956-contrasto-colore-e-focus-nel-form
fixes:
1. made ScrollToTop button tabbable
2. added border to buttons and to search button in header to create triple outline on focus
--> dark bg - light button = inner dark border + outer light shadow
--> light bg - dark button = outer dark outline + inner light shadow
--> dark bg - dark button = inner light shadow
--> light bg - light button = outer dark outline + middle light shadow + inner dark border
3. styles for buttons on focus-within for correct color and correct contrast with text

fix: focus of buttons + focus of inputs + contrast of buttons

---

src/components/ItaliaTheme/View/PersonaView/PersonaDocumenti.jsx

fixed the layout so the Attachments component is not inside two card-wrappers

fix: document cards layout for ct persona

---

RELEASE.md
package.json
src/config/italiaConfig.js
yarn.lock

[v11] Risolve 
https://redturtle.tpondemand.com/restui/board.aspx?#page=bug/66740
Risolto un problema con l'aggiunta di un blocco di testo attraverso il selettore dei blocchi all'interno dei campi a blocchi delle form dei Content Type che li prevedono.
https://redturtle.tpondemand.com/restui/board.aspx?#page=bug/66535
Risolto un problema che impediva la visualizzazione della sidebar dei blocchi all'interno di alcuni campi a blocchi delle form dei Content Type che li prevedono, impattandone l'utilizzo e la modifica.

fix: rollback volto-blocks-editor to a compatible version, fix volto-blocks-editor text block is always slate in it's block chooser

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Common/SearchFilters/TextFilter.jsx
src/components/ItaliaTheme/Blocks/UOSearch/Body.jsx

https://redturtle.tpondemand.com/entity/64948-label-form-di-ricerca-solr-mancante
did not use the id of the component as the search components pass it as "filterOne", etc. which might be repeated within the page if there's more than one search block

fix: added label to TextFilter component

---

RELEASE.md
src/customizations/volto/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx

Changed the way **byweekday** is calculated.
If the state of the widget undergoes some changes for only some fields or the state of the widget is not updated correctly with the changes made, **byweekday** will always come out from that definition as null. (see the diff)
However, if we're using the byweekday parameter when setting a monthly recurrence, byweekday being null means that the form value for the weekday field is set as the current day (736-740):
`   case 'weekdayOfTheMonthIndex':
var week_day = byweekday ? byweekday[0] : currWeekday; //get day from state. If not set get current day
//set nth value
formValues.byweekday = value ? [week_day.nth(value)] : null;
break;` 
that creates an issue whenever the weekday is not changed, but the index of the weekday is.
e.g. first monday of …

fix: changed byweekday parameter management in recurrence widget

---

RELEASE.md
src/components/ItaliaTheme/BrandText/BrandText.jsx

è necessario avere anche questa parte sul BE
https://github.com/collective/collective.volto.sitesettings/pull/3
Nel pannello di controllo è stata aggiunta l'opzione 'Nascondi il titolo' che permette di nascondere il titolo (come fatto su Nuovo Circondario Imolese) nell'header del sito principale. 
Per i sottositi il titolo continua a funzionare con le stesse regole di prima. 
us: 66434

feat: optionally hide Site Title from control panel

---

package.json
yarn.lock

C'era un problema nel widget del criterio posizione del blocco elenco. 
Se in un blocco elenco mettevo piu di un criterio posizione, poi cancellavo un criterio che non era l'ultimo, in realtà quello rimaneva, perchè le subrequest per avere il link al contenuto scelto dall'objectbrowser avevano come identificativo l'indice dell'array. 
Ora il problema è stato risolto nell'addon https://www.npmjs.com/package/volto-querywidget-with-browser
US: 65237

fix: multiple query widget paths

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Callout/Edit.jsx
src/components/ItaliaTheme/Blocks/Callout/View.jsx
src/theme/bootstrap-override/bootstrap-italia/_callout.scss

[US66862](https://redturtle.tpondemand.com/entity/66862-visualizzazione-mobile-del-blocco-callout)
Il problema qua è che anche sul layout di Bootstrap Italia questo blocco è fatto male
Per cui ho cambiato View ed Edit del blocco aggiungendo la linea di decorazione come un ulteriore span.
[DESKTOP]
[MOBILE]

fix: fixed mobile style of callout block

---

RELEASE.md
src/theme/ItaliaTheme/Blocks/_smallblockLinkstemplate.scss

height 100% set for better visualization .

Small blocks links image height

---

RELEASE.md
src/components/ItaliaTheme/View/PaginaArgomentoView/PaginaArgomentoView.jsx

Sostituito `content.caption` a `content.image_caption`

Didascalia per l'immagine di testata CT Argomento

---

RELEASE.md
theme/ItaliaTheme/Blocks/_imageCardTextBlock.scss

[US64104](https://redturtle.tpondemand.com/entity/64104-rivalutare-dal-punto-di-vista-delle)
Ho rimosso una regola che impediva alla card di formattare il testo con draft

chore: updated imageCardText block with draft formatting

---

src/components/ItaliaTheme/Blocks/TextCard/CardWithImage/Edit.jsx
src/components/ItaliaTheme/Blocks/TextCard/CardWithImage/View.jsx

Now the paths to internal links use “design-comuni-plone-theme/components/ItaliaTheme” instead of “./NameOfTheComponent”. This is required for theme customizations to work properly.

fix: Card with image paths

---

src/components/ItaliaTheme/MegaMenu/MegaMenu.jsx

This commit fixes the ARIA role hierarchy inside the main navigation menu.
The "ul" element uses role="menubar", which requires its direct children to be elements with role="menuitem" (or wrapped in elements with role="none" containing menuitem). Previously, the links inside dropdown menus were missing the correct role, triggering accessibility errors in tools like Lighthouse and axe.
Changes made:
•	Added role="menuitem" to all "a" elements inside dropdowns that are part of the navigation bar
•	Kept role="none" on the surrounding "li" elements, as recommended by the WAI-ARIA specification
All that to add this to the dropdown menu:
ERROR:

fix: add role='menuitem' to links inside dropdown to fix menubar role hierarchy

---

RELEASE.md
src/theme/ItaliaTheme/Blocks/_smallblockLinkstemplate.scss

[BUG69301](https://redturtle.tpondemand.com/entity/69301-blocco-link-con-immagine-in-una)

fix: fixed image focus of smallBlockLinkTemplate

---

RELEASE.md
src/theme/ItaliaTheme/Blocks/_completeBlockLinkstemplate.scss

https://v3.io-comune.redturtle.it/test-giulia/blocco-link-completo-con-img

fix: image in template "Blocco link completo" 

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/CardWithImage/CardWithImageDefault.jsx
src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/Commons/ListingImage.jsx
src/components/ItaliaTheme/Blocks/Listing/CompleteBlockLinksTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/InEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/RibbonCardTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/SimpleCard/Card/SimpleCardDefault.jsx
src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateCompact.jsx
src/components/ItaliaTheme/Blocks/Listing/SimpleCard/SimpleCardTemplateOneForRow.jsx
src/components/ItaliaTheme/Blocks/TextCard/SimpleCard/Edit.jsx
src/components/ItaliaTheme/Blocks/TextCard/SimpleCard/View.jsx
src/theme/ItaliaTheme/Components/_card.scss

Risolto vari problemi di accessibilità
1. [bug66918](https://redturtle.tpondemand.com/entity/66918-a11y-titolo-blocco-card-semplice) sostituito tag h3 con h2 per la card semplice, semanticamente non era corretto all'interno della pagina
2. [bug66915](https://redturtle.tpondemand.com/entity/66915-a11y-titoli-blocchi-elenco) sistemato titoli per le card dei blocchi elenco che se non mostravano alcun titolo del blocco semanticamente non andavano bene
3. [bug66919](https://redturtle.tpondemand.com/entity/66919-a11y-immagini-decorative) sistemati i conflitti per le immagini decorative dei listing

fix: fixed a11y titles and images attributes

---

package.json
yarn.lock

Aggiornato volto-venue alla versione [4.1.2](https://github.com/collective/volto-venue/releases/tag/v4.1.2)

chore: updated volto-venue v4.1.2

---

package.json
src/components/ItaliaTheme/Blocks/Common/SearchFilters/SelectFilter.jsx
yarn.lock

aggiornata la versione di volto-form-block da 3.12.0 a 3.13.0 per avere nel csv esportato dai blocchi form, anche la colonna degli allegati
Questo richiede anche un aggiornamento di https://github.com/collective/collective.volto.formsupport) alla versione 3.3.0
(Richiesto dalla RER)

chore: updated volto form block 3.13.0

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/BandiInEvidenceTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/RibbonCardTemplate.jsx
src/components/ItaliaTheme/Blocks/Listing/SimpleCard/Card/SimpleCardDefault.jsx
src/components/ItaliaTheme/Blocks/Listing/TemplatesSkeletons/BandiInEvidenceTemplateSkeleton.jsx

- Il titolo è sempre reso cliccabile.
- Il link "Vedi" è contrassegnato con aria-hidden="true" e tabindex="-1", in modo da non essere più raggiungibile da tastiera o screen reader.
**Motivazione**
- In questo modo si evita la duplicazione dei link e si garantisce un comportamento coerente e accessibile.

fix: read more a11y

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Listing/CardWithSlideUpTextTemplate.jsx

Nel blocco CardWithSlideUpTextTemplate è stato modificato il comportamento della navigazione con il lettore di schermo.
Ora il focus non passa più sull’intero card né sul pulsante “Vedi/Read More”, ma soltanto sul titolo.
In questo modo, il titolo viene letto correttamente e, se necessario, il lettore di schermo può leggere anche i testi circostanti, senza perdita di informazioni.
Inoltre, è stato aggiunto un attributo aria-hidden all’elemento “Vedi/Read More”, che quindi non viene preso in considerazione dagli screen reader.

fix: card with slide text a11y

---

RELEASE.md
src/components/ItaliaTheme/Blocks/Common/SearchFilters/DateFilter.jsx
src/components/ItaliaTheme/Blocks/Common/SearchFilters/SelectFilter.jsx
src/components/ItaliaTheme/Blocks/Common/SearchFilters/TextFilter.jsx
src/components/SelectInput/SelectInput.jsx
src/theme/ItaliaTheme/Blocks/common/_searchBlockFilters.scss

Migliorati i campi di input Text, Select e DateRange con la possibilità di applicare una label sempre visibile.
[US 69727](https://redturtle.tpondemand.com/entity/69727-a11y-label-sempre-visibile-blocco-ricerca)
[PRIMA]
[DOPO]
Aggiunto anche alcuni fix per quanto riguarda la label che già c'era sul campo di input text
->

chore: updated text, select and date input filter with label props

---

RELEASE.md
src/components/ItaliaTheme/manage/Widgets/HtmlSlateWidget.jsx

Risolto un errore nel widget HtmlSlateWidget che impediva l’inserimento corretto dei link quando si usavano percorsi interni per file e immagine.

fix: HtmlSlateWidget to link files

---

package.json
yarn.lock

Riferimento alla [us68303](https://redturtle.tpondemand.com/entity/68303-nelle-pubblicazioni-il-campo-abstract-non) per filtrare i blocchi nei CT di tipo form
!In attesa dell'ultima release con questa [fix](https://github.com/collective/volto-blocks-widget/pull/10) di volto-blocks-widget

chore: updated volto-blocks-widget v3.4.7

---

RELEASE.md
locales/de/LC_MESSAGES/volto.po
locales/en/LC_MESSAGES/volto.po
locales/es/LC_MESSAGES/volto.po
locales/fr/LC_MESSAGES/volto.po
locales/it/LC_MESSAGES/volto.po
locales/volto.pot
src/config/italiaConfig.js
src/customizations/volto-form-block/components/FormResult.jsx
src/overrideTranslations.jsx

[US69506](https://redturtle.tpondemand.com/entity/69506-blocco-form-messaggio-con-limite-di)
Aggiunta configurazione per mostrare il messaggio di ringraziamenti insieme al messaggio di notifica del limite di iscrizioni superate del blocco form, i messaggi inoltre sono stati resi generici

chore: updated warning form block message and configured alert with thank-you message

---

RELEASE.md
src/components/ItaliaTheme/index.js
src/components/ItaliaTheme/manage/Widgets/ConditionallyRequiredDateWidget.jsx
src/config/Widgets/widgets.js

da mergiare con questa di BE https://github.com/RedTurtle/design.plone.contenttypes/pull/314
https://redturtle.tpondemand.com/entity/69927-rendere-condizionale-lobbligatorieta-della-data-di

feat: made data_inizio_incarico conditional

---

RELEASE.md
src/components/ItaliaTheme/View/Commons/PageHeader/PageHeaderTassonomiaArgomenti.jsx

fix: Updated heading from H5 to H2 for improved hierarchy

---

src/components/ItaliaTheme/Blocks/BandiSearch/Body.jsx

In v2 è possibile definire nel blocco bandisearch dei filtri iniziale, se i filtri iniziali hanno dei valori, il menu in pagina dell'utenet viene completamente ignorato, perchè al backend venivano mandati sia i filtri dell'utente che quelli del filtro iniziale.
Con questa modifica, i filtri dell'utente sovrascrivono quelli iniziali, sul singolo ndice

fix: bandisearch
